### ISSUE TITLE
Product media size 515 in all devices

### ISSUE THREAD

**Issue by fernandadasneves** [SAP/spartacus#10009]
Adding product multiple sizes of media on the product cockpit is not reflecting the size in Spartacus.
if it´s mobile or widescreen the size of the media is 515, regardless. 
This is also happening for the demo store.

Version: Spartacus 3.0.0-next.6

Desktop:

OS: Windows
Browser: Chrome, Edge
Version: last version

Smartphone:

Device: Android / IOS actual versions
OS: Actual Version
Browser chrome / safari
Version Actual versions

1.Go to the storefront of any device and search for any product
2.Click with the right button of the mouse and select "open image in new tab" option
3. A new image tab will appear informing media size - Medias (515x515)

**Comment by tobi-or-not-tobi** [comment]
@fernandadasneves thanks for reporting! There are two issues with the product media:
- we took the wrong assumption in the past the img srcset is taken care of selecting the right image; this is not the case, as the browser can only use media queries (based screen sizes) to select a specific source. 
- even with the <2.0 approach, where we selected specific formats for specific layouts (i.e. thumbnail for the search-box), it was failing, as we'd still add all the images to the srcset, and hence the browser would select the source based on the screen size

There are other related  issues regarding pixel density (#9680) that is out of scope of this ticket, but certainly on the radar. We take this ticket as a high priority ticket. 

We're fixing this in a few iterations:
- patch a fix to 3.0-RC and 2.1.x 
  - include specific formats for most product related layouts. i.e. render the product `thumbnail` format in search-box, product `cartIcon` format in cart item, etc.
  - limit the generated images in the `srcset` to all formats up to the given format (if any). This will solve the issue that larger image would still be selected by the browser

Additionally, we're planning on these enhancements going forward (3.x release)
- configurable image format per component, so that you can drop out on the hardcoded format
- configurable pixel density vs introducing sizes / picture element structure (if needed, but this would cause a breaking change)
