### ISSUE TITLE
Include B2B tests on smoke and regression suites

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#10014]
B2B tests need to run as part of smoke and regression testing

**Comment by Platonn** [comment]
## Smoke vs. regression
IMO b2b checkout should be part of Smoke, but I'd leave other stuff in regression (becuase they take too much time:

| time | test | should be fixed in |
|-|-|-|
||**SMOKE:**||
21 sec | `b2b\checkout\b2b-account-checkout-flow.e2e-spec.ts` | |
38 sec | `b2b\checkout\b2b-credit-card-checkout-flow.e2e-spec.ts` |
||||
||**REGRESSION:**||
fails | `b2b\accessibility\tabbing-order.e2e-spec.ts` | https://github.com/SAP/spartacus/issues/10064
84 sec | `b2b\checkout\b2b-replenishment-checkout-flow.e2e-spec.ts` | |
fails | `b2b\my-account\b2b-replenishment-order-details-flow.e2e-spec.ts` | https://github.com/SAP/spartacus/issues/10065 |
8 sec | `b2b\my-account\b2b-replenishment-order-history-no-orders-flow.e2e-spec.ts` | |
22 sec | `b2b\my-account\b2b-replenishment-order-history-orders-flow.e2e-spec.ts` | |
2:20+ min each | `\b2b\my-company\...` (budgets, cost-centers, purchase-limits, units, user-groups, users) | speed  up: https://github.com/SAP/spartacus/issues/10067 |
36 sec | `b2b\order-approval\b2b-order-approval.e2e-spec.ts` | |

### Splitting `/b2b` folder to smoke and regression
Currently the structure of e2e looks:
- accessibility
- b2b
  - accessibility
  - checkout
  - my-account
  - my-company
  - order-approval
- mobile
- regression
- smoke
- vendor
  - cds

I suggest splitting the `/b2b` folder into `b2b/smoke` and `b2b/regression`:
- b2b
  - smoke
    - checkout
  - regression
    - replenishment (contain previous `my-account/b2b-replenishment...` and `checkout/b2b-replenishment-checkout-flow`
    - accessibility
    - my-account
    - my-company
    - order-approval


## 2 app builds and 2 cypress runs:
Running b2b storefront requires having separate build of the shell app with env var `SPARTACUS_B2B=true`  to import b2b configs and modules. Therefore we need to start app second time (with env var) and run cypress again (but for different files - b2b ones):

For example in `ci-scripts/e2e-cypress.sh`:
```diff
    echo "Running Cypress end to end tests for suite: $SUITE"
    if [[ $SUITE == 'regression' ]]; then
        yarn e2e:cy"${INTEGRATION}":start-run-ci"${CI_ENV}"
+       yarn e2e:cy:b2b"${INTEGRATION}":start-run-ci"${CI_ENV}"
    else
        yarn e2e:cy"${INTEGRATION}":start-run-smoke-ci"${CI_ENV}"
+       yarn e2e:cy:b2b"${INTEGRATION}":start-run-smoke-ci"${CI_ENV}"
    fi
```

### Caveats
Running cypress 2 times will cause 2 separate records in the cypress dashboard.

**Comment by Platonn** [comment]
Two things that are unusual and need special care:
- we don't want to introduce more cypress..b2b.json configs suffixed with all evironment names - decided to pefrorm workaround (run b2b e2e only for 2005 env..... and if possible 2011 too - to avoid confusion in the near future when we start testing 2011). Note: we want to improve and drop the hardcoded logic for 2005 and 2011 in https://github.com/SAP/spartacus/issues/10160
- running b2b e2e tests requires:
  - stopping the previously started application
  - starting the application again, but with process env var `SPARTACUS_B2B=true` (so in the build time the `B2bStorefrontModule` is imported instead of `B2cStorefrontModule`).

**Comment by giancorderoortiz** [comment]
Getting a 68% pass rate when running b2b tests localhost
Waiting for https://github.com/SAP/spartacus/issues/10263 and https://github.com/SAP/spartacus/issues/10231

https://dashboard.cypress.io/projects/k3nmep/runs/7491

**Comment by giancorderoortiz** [comment]
Well, in headless mode, after some tests were disabled, I see that the b2b test suite passes. 
(See https://github.com/SAP/spartacus/issues/10271)

However, the situation is not ideal. This should be the exception rather than the rule. 
Accept for now, given timeline to release. Significant improvements are needed in this area.  
@Xymmer , @hackergil , @zebercut, @dunqan  

Recorded Run: https://dashboard.cypress.io/projects/k3nmep/runs/7786
![Screen Shot 2020-12-11 at 3 36 22 PM](https://user-images.githubusercontent.com/46171897/101952716-17dfb680-3bc7-11eb-9fba-63ab6e37a723.png)
