### ISSUE TITLE
 Random image on the bottom of product page

### ISSUE THREAD

**Issue by fernandadasneves** [SAP/spartacus#10024]
An image appears at the bottom on the product list after a search.

Version: Spartacus 3.0.0-next.6

This issue is even on the demo site of Spartacus.
https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/search/sony

Desktop:
OS: Windows
Browser: Chrome, Edge
Version: last version

Screen Shot:
<img width="224" alt="taladradora" src="https://user-images.githubusercontent.com/75036418/100366638-5ab76100-3001-11eb-9754-b4b41e77b18c.png">

**Comment by fernandadasneves** [comment]
Hello,

can someone give me an update?

thank you.

**Comment by sebastianfdez** [comment]
You have to clean the components/slots of the search page from smart-edit

**Comment by bgambocjaviniar** [comment]
sample data PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/158

kept the top banner, but removed the big image at the bottom of the search page

- fixes electronics and powertools catalogues

**Comment by giancorderoortiz** [comment]
This issue has been fixed in latest develop branch. (may 17. 2021). 
Need to backport? @Xymmer @hackergil 

See https://cx-qa16181492.eastus.cloudapp.azure.com:444/powertools-spa/en/USD/search/drill

![Screen Shot 2021-05-18 at 10 39 27 AM](https://user-images.githubusercontent.com/46171897/118671364-65d79680-b7c5-11eb-9f4a-90249adc71ce.png)

**Comment by giancorderoortiz** [comment]
Closing as this issue has been fixed.
