### ISSUE TITLE
Failing e2e b2b\my-account\b2b-replenishment-order-details-flow.e2e-spec.ts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10065]
1. run `yarn e2e:cy:open:b2b`
2. in the cypress menu run `b2b\my-account\b2b-replenishment-order-details-flow.e2e-spec.ts`

![obraz](https://user-images.githubusercontent.com/4001059/100467571-f9f85900-30d2-11eb-887f-d3298b94f3ab.png)

**Comment by bgambocjaviniar** [comment]
PR: GH-10074

Test was failing because local storage did not carry over the next `it`. This should have been automatically done by cypress as stated in their documentation. Moreover, it is very strange that it started failing consistently, because just last week, I ran the b2b suite for a ticket and it was working perfectly. Patrick can confirm as well.

**Comment by bgambocjaviniar** [comment]
3.0.x PR: https://github.com/SAP/spartacus/pull/10190
