### ISSUE TITLE
Date Picker does not work on Safari

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#10062]
**Describe the bug**
Date Picker component is rendered as a normal text field on Safari. It can still be used as a text field but formats are unclear and default dates do not work (ie. interpreted as undefined).

**Tell us the version of Spartacus**
- Library version: 3.0-rc.1

**To Reproduce**
1. Go to create Budget
2. Can see "undefined" in Start and End fields.

![image](https://user-images.githubusercontent.com/11735817/100460001-bb5ca180-30c6-11eb-821b-229f79607db8.png)

Note: You can still create a budget if you type dates formatted like in the screenshot below.

![image](https://user-images.githubusercontent.com/11735817/100460069-d7f8d980-30c6-11eb-9669-6971bd9f78bc.png)

**Expected behavior**
Ideally, date picker would work. But as its not supported in Safari, there should be a fallback. The simplest solution would be to have placeholders that indicate format (ie. yyyy-mm-dd).

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Comment by tobi-or-not-tobi** [comment]
I'm seeing a number of issues with the date picker. This is related to the standard behaviour of the date picker ([and newer datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)).

- The date control as well as the newer datetime-local picker control use the user OS specified date. The associated date format (i.e. dd.mm.yyyy in german) is used in the placeholder of the input which doesn't necessarily align with the storefront language. This seems to be an acceptable deviation, given that the html controls have been designed like this. 
- The element input `type="date"` is not supported by all browsers. The fallback is a standard text input, however the user needs a steer on the input format as well as we should provide a validation. 
- We cannot simulate the same placeholder as the behaviour on other browsers, simply because we do not have access to the OS locale settings. We can only access the browser language (`navigator.language`), but this is not necessarily the same as the storefront language. 
- Regardless of the language we take as an input, implementing date formats will introduce complexity: 
  - implement language specific placeholder (i.e. `dd.mm.yyyy` vs `mm-dd-yyyy`)
  - implement language specific validation
  - implement language specific converters, converting from the locale [to the standard format](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#Local_date_and_time_strings)

Based on this we can take two directions: 
1. Implement a localised date placeholder, validator and converter to support the storefront language date format. This could be used for safari only but might even replace the native date picker on all devices. It's not necessarily bad, but it's considerable  effort that is not aligned with standards
2. Use a _single_ date placeholder, format (and optional converter) as a fallback for browsers that don't support the native date picker.

**Comment by tobi-or-not-tobi** [comment]
Based on the former input the following would unblock us very quickly: 
1. add a placeholder: `yyyy-mm-dd`
2. add a validator for the value base don this placeholder, that should work for [the standard format](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#Local_date_and_time_strings)

There's no need to build a converter as we're aligning with the default value format

~~Regarding validation, there's unfortunately no native validation available since the `pattern` attribute is also not supported by safari.~~ Safari actually supports the pattern property.

**Comment by tobi-or-not-tobi** [comment]
reopen as maintenance fix isn't done yet

**Comment by tobi-or-not-tobi** [comment]
Done
