### ISSUE TITLE
[Verify backend fix when it will be done] Unit Shipping Address missing 2nd address in list

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#10060]
**Describe the bug**
When you add a shipping address to a unit without a 2nd address, the string looks funny in the list since the 2nd address placeholder is empty.

**Tell us the version of Spartacus**
- Library version: 3.0-rc.1

**To Reproduce**
1. Create a unit address without a 2nd address line.
2. See created address in list.

**Expected behavior**
We should not see the placeholder for the 2nd address if it is empty.

**Screenshots**

![image](https://user-images.githubusercontent.com/11735817/100459584-fca08180-30c5-11eb-8754-fb71cc95bd05.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Comment by wangzixi-diablo** [comment]
Hello Caine,

I made a trouble shooting and found out that the unnecessary place holder "," , is populated in backend and returned to Spartacus via OCC API via field "formattedAddress". IMHO it's better to have this issue fixed in OCC API implementation side? But I'm not sure, what's your opinion?

<img width="783" alt="clipboard1" src="https://user-images.githubusercontent.com/58975336/103876321-776dab00-510e-11eb-8e41-d233deb28d90.png">

<img width="815" alt="clipboard2" src="https://user-images.githubusercontent.com/58975336/103876313-7472ba80-510e-11eb-8be1-b44405427293.png">


Best Regards,
Jerry

**Comment by wangzixi-diablo** [comment]
after discussion with Caine, this issue should be fixed in OCC API implementation side. JIRA issue created: https://cxjira.sap.com/browse/CLC-2423

**Comment by giancorderoortiz** [comment]
Issue no longer seen. 
Tested with Spartacus 3.0 in demo server. 

![Screen Shot 2021-06-06 at 11 05 28 AM](https://user-images.githubusercontent.com/46171897/120929546-76d64200-c6b7-11eb-8cae-a278c9696b9c.png)
![Screen Shot 2021-06-06 at 11 07 20 AM](https://user-images.githubusercontent.com/46171897/120929547-76d64200-c6b7-11eb-8908-035e28558700.png)
