### ISSUE TITLE
RC. Validate Functionality and Integration with Qualtrics

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10078]
Does Spartacus 3.0 RC1 integrates with Qualtrics? 
2005 backend?
2011 backend? 

Please provide happy path screenshots for future reference. 
Test with CCV2 or Linux Server? TBD

**Comment by bgambocjaviniar** [comment]
This is a 3rd party integration and not dependent to the commerce modules. Spartacus just needs the deployment code from 'Qualtrics' to integrate with Spartacus, however please see the provided screenshot for both environments.

Moreover, this was already tested due to what was asked in here https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=Endgame+for+releasing+3.0 but there was no tickets to submit a screenshot, so I'll be using this issue. _Another thing is Bill can confirm as well that the Qualtrics team confirmed that the integration is working perfectly as we had a call on Thursday/Friday about a new `feature` for Qualtrics that 'should' be implemented in the near future_

----------------------- big happy path is only when you can view 'creatives'/'intercepts' when the Qualtrics deployment code is added to Spartacus. All the heavy load comes from Qualtrics as Spartacus just helps enable communication with the services ---------------

steps to integrate Qualtrics to Spartacus: https://sap.github.io/spartacus-docs/qualtrics-integration/#page-title

1 - Go to any product details page and it should fire those creatives/intercept as we have a QualtricsComponent hooked into one of the content slot of a product details page. Those modal come from Qualtrics and is not from Spartacus.

2005: **using dev0-azure / develop**
<img width="1440" alt="Screen Shot 2020-11-29 at 1 20 42 PM" src="https://user-images.githubusercontent.com/29099466/100550140-d4d82780-3245-11eb-926c-a8c7a84f7ff8.png">


2011: **using dev4-azure (which is 2011) I tried `qa16181492` server but that's running on 2005.2 / develop**
<img width="1439" alt="Screen Shot 2020-11-29 at 1 28 27 PM" src="https://user-images.githubusercontent.com/29099466/100550281-e66dff00-3246-11eb-8b06-fa3c721cdaf7.png">

**Comment by Xymmer** [comment]
confirmed we tested it
