### ISSUE TITLE
Add TODO Spratacus in comments for component deprecations

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10138]
In component deprecations, some comments are missing the `TODO_SPARTACUS` keyword.

- Add it to all the migrations where it is missing

ex:
`comment: '' placeOrderSubscription' property was removed and replaced',`

- Becomes

`comment: ' ${TODO_SPARTACUS} 'placeOrderSubscription' property was removed and replaced'`,

**Comment by Xymmer** [comment]
after chatting with Louis, it's strongly preferable that this be fixed for 3.0

**Comment by plabadie** [comment]
After investigation with @LTiger14 , the issue is rather present only for component deprecation comments added to html.  The solution in the PR is therefore only to add `${TODO_SPARTACUS}` for component deprecation comments in html.

To smoke test:
run `yarn clean` and `yarn test` in the schematics project folder.
