### ISSUE TITLE
Error in building spartacussampledata extension in backend

### ISSUE THREAD

**Issue by enginvolkan** [SAP/spartacus#10133]
**Describe the bug**
I am trying to install spartacussampledata extension to the backend as described in this [https://sap.github.io/spartacus-docs/pre-release-information/#building-a-b2c-store-requires-angular-10](url) for 2011 version.
I am going for a manual setup instead of the recipe method since I already have my backend up and running.
I downloaded the zip file and extracted the spartacussampledata folder to bin/custom directory.
I updated the localextensions.xml and run ant all. I received the following error:
`de.hybris.bootstrap.config.BootstrapConfigException: Extension 'spartacussampledata' doesn't specify a path and no scanned extension was matching the name. Please check file C:\hyb2011\hybris\core-customize\config\localextensions.xml.`

I renamed the folder to spartacussampledataaddon, updated localextensions.xml and had no issues with the ant build.

I guess you should either update the documentation or you should update the extension name in the following files: extensioninfo.xml, project.properties.template, buildcallbacks.xml to keep spartacussampledata as the extension name.

**Tell us the version of Spartacus**
SAP Commerce 2011

**Comment by Xymmer** [comment]
Hi @enginvolkan , in that page, https://sap.github.io/spartacus-docs/pre-release-information/#adding-the-new-sample-data
the recipe or your local extensions file should point to **spartacussampledata** instead of *addon
renaming the folder also worked but it should be other way around

you can also remove the spartacussampledataaddon entry in your addons section, as the Spartacus sample data is now just an extension, not an addon

Our 3.0 docs will be updated accordingly, thanks for the feedback.

**Comment by enginvolkan** [comment]
Hi Bill,
The issue is resolved with the new version of the zip file in rc1. 
Thanks

**Comment by timothy2005** [comment]
I met the same issue, and solved it:

Please check :

1,
hybris/bin/custom/spartacussampledata/extensioninfo.xml
`<extension ... name="spartacussampledata">`

2,
hybris/config/localextensions.xml
`<extension name='spartacussampledata' />`

Above extension name must be the **same**!
I guess you have **different** ones
one is spartacussampledata (extension)
and the other is spartacussampledata**addon** (addon)

Because Spartacus 3.0 and later use the new Spartacus sample data extension (not the addon). 
For now Spartacus provides both for download. However, the sample data extension will be the only one updated in the future.
Both will work for older releases, the new extension contains updates to b2b sample data

Here is URL of spartacussampledata.zip version 3.0.0:
https://github.com/SAP/spartacus/releases/download/storefront-3.0.0/spartacussampledata.2005.zip
