### ISSUE TITLE
IOS 13 and below has undefined Dates in the order-overview component

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10147]
Hardware:
iPad Pro. 12.3.1.
Browser: Safari

**Steps to Reproduce:**

1. Using iPad Pro, open safari and navigate to ccv2 Spartacus 3.0 RC1 Electronics storefront.
2. Login.
3. Add items to cart.
4. Complete checkout.
5. Wait one minute.
6. Visit Order History and see the order history details for the purchase completed in Step 4.

**Expected Results:** 
5. Placed On date contains a date in a readable format. 

**Actual Results:** 
5. Placed On says: "Date undefined undefined"

**Comment by giancorderoortiz** [comment]
![UndefinedDate](https://user-images.githubusercontent.com/46171897/100731809-e03c6780-3399-11eb-8a06-5ec5010352b7.png)

**Comment by Xymmer** [comment]
is it just ipad pro? or general issue?

**Comment by bgambocjaviniar** [comment]
PR: GH-10238

undefined happens for iOS version 13 and below because it does not work well with ISO String ending with :0000

QA - steps:

**- requirements** : need to be using a IOS phone that has iOS version of 13 or older

- use dev0-azure and login as a user for b2b and b2c
- go to order details and make sure the date under `place on` is not undefined
- go to replenishment details for b2b, and make sure `start on` and `next order date` are not undefined

**Comment by bgambocjaviniar** [comment]
P.S. 
1- can test using a real mobile device, but you need to be able to create a tunnel from your device to use localhost
2 - can use browserstack with the following steps bellow:

step 1: enable browserstack local
step 2: run spartacus using yarn start --disable-host-check
step 3: accept the backend certificate (whichever backend you’re using)
step 4: http://bs-local.com:4200 should work now!

![Screen Shot 2021-06-15 at 10 06 04 AM](https://user-images.githubusercontent.com/29099466/122068945-cbb63e80-cdc2-11eb-9753-36484525f4be.png)

**Comment by giancorderoortiz** [comment]
![ipadpro](https://user-images.githubusercontent.com/46171897/123990729-078efd80-d998-11eb-9b35-64756b498c34.png)

**Comment by giancorderoortiz** [comment]
Issue fixed
