### ISSUE TITLE
Auto scroll to middle or bottom of the page when navigating to new page.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10143]
**Describe the bug**
Auto scroll to middle or bottom of the page when navigating to new page.
In many situations where I navigate to a new page, the pages is displayed scrolled down.  It is disorienting for the user and moreover we can't see success/error messages after some actions.

**Tell us the version of Spartacus**

test env https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (see #10030)

**Steps to reproduce:**

I reproduced on:
* iPhone 6s on iOS 14
* Chrome in iPhone 7+ view in dev tools on Mac.

I've seen this happen on pure desktop in the past too, but I can reproduce it consistently on mobile viewport.
See videos in attachment. (captured on chrome/mac)

Expected behavior
New pages appear at the top of the page as intended.

**Error videos:**

[Bug-videos.zip](https://github.com/SAP/spartacus/files/5619091/Bug-videos.zip)

**Comment by tobi-or-not-tobi** [comment]
This happens since we dropped the [enabled `scrollPositionRestoration`](https://angular.io/api/router/ExtraOptions#scrollPositionRestoration). While the standard enabled scrollPositionRestoration was pretty bad in a lot of situations, a complete lack of scrollPositionRestoration is also not great. We need to quit likely implement a custom restoration that takes the context into account.

**Comment by tobi-or-not-tobi** [comment]
The reason why the `scrollPositionRestoration` was dropped, is that it gives some pretty annoying behaviour in the following situations: 
- when you use child routes, the `scrollPositionRestoration` kicks in when you change the child routes
- when you navigate from route to route, the `scrollPositionRestoration` kicks in even if the new view is already in the viewport 

The `scrollPositionRestoration` is basically to aggressive, as it will always move you to the precise `top:0` position

**Comment by Parthlakhani** [comment]
Should we follow this approach? :
Enable restoration for all except for
- URL change in query parameter (which is after `?`)
- Any changes within URL `/organization/`

If we can follow this approach:
- where should we implement this logic?
- how to keep it separately for storefrontlib and organization (how to prepare it overridable)

**Comment by Pucek9** [comment]
https://stackoverflow.com/questions/67068117/spartacus-storefront-after-scrolling-down-list-of-results-and-then-clicking-on

**Comment by Zeyber** [comment]
Bumped the priority on this issue to urgent as there is some demand for it.

**Comment by giancorderoortiz** [comment]
I don't see a fix. 
Deployed localhost, dev branch (June 10).  Mac OS. Chrome. 

- Search for "cam"
- Scroll down to the very last SKU listed. 
- Click on it. 
- What appears is PDP  scrolled down as well. 

Expected: PDP scrolled up so that header is visible. 

![Screen Shot 2021-06-10 at 4 06 27 PM](https://user-images.githubusercontent.com/46171897/121590270-238d2800-ca06-11eb-9fc5-f6d03090444b.png)

![Screen Shot 2021-06-10 at 4 06 13 PM](https://user-images.githubusercontent.com/46171897/121590282-25ef8200-ca06-11eb-8344-a3301fcdac52.png)

**Comment by giancorderoortiz** [comment]
Waiting for confirmation from @Xymmer, @hackergil.

**Comment by giancorderoortiz** [comment]
@Zeyber are there any backward compatibility concerns as to why the fix for this issue is not enabled by default?

**Comment by giancorderoortiz** [comment]
@hackergil agrees with solution presented. 
Works as designed, then.
