### ISSUE TITLE
Bundles: Styling of 'Qty' text

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#10630]
Update by Uli:
1. fixed
2. fixed
**3. Text 'Qty' still displayed above quantity stepper instead of left of it.**

Some minor issues concerning styling and wording in bundles:

1. The "more"/"less" links should use lower case "more"/"less" not "More"/"Less".

2. Mobile Version: the attributes should be centered. Currently they are left aligned:
Examples:
Implementation left aligned:
![Impl Left aligned](https://user-images.githubusercontent.com/54309425/104008391-ae44cf00-51a9-11eb-9d5e-b0178a73efc1.png)

Should be centered as in mock-up:
![mockup centered](https://user-images.githubusercontent.com/54309425/104008420-bdc41800-51a9-11eb-8174-aceae24ba878.png)

3. "Qty" should be left of quantity control not above

Implementation:
![impl qty](https://user-images.githubusercontent.com/54309425/104008488-d0d6e800-51a9-11eb-8891-a91bba32218f.png)

Mockup: 
![mockup qty](https://user-images.githubusercontent.com/54309425/104008532-d9c7b980-51a9-11eb-9d9f-dfbf0ebd967d.png)

4. Wording: "Deselect" should be "Remove"
Implementation:
![Impl deselect](https://user-images.githubusercontent.com/54309425/104008581-e64c1200-51a9-11eb-9d36-d961a4debaed.png)

Mockup:
![Mockup remove](https://user-images.githubusercontent.com/54309425/104008592-e9470280-51a9-11eb-88c7-e2b127454332.png)

**Comment by luklus** [comment]
@steinsebastian 

1. Fixed

![Zrzut ekranu 2021-01-11 094035](https://user-images.githubusercontent.com/12393718/104160252-1d603480-53f1-11eb-965b-cbb0641bca29.png)


2. Fixed

![Zrzut ekranu 2021-01-11 093756](https://user-images.githubusercontent.com/12393718/104160075-c8242300-53f0-11eb-8b37-980e8d5e0f26.png)


3. To decide: there is also a vertical option on wirefarms. I used it because it allows you to save some space that is missing (picture)

![Zrzut ekranu 2021-01-11 095235](https://user-images.githubusercontent.com/12393718/104161667-8779d900-53f3-11eb-8262-5b5ff4e72ee1.png)



4. To decide: with wireframes: on multiselect we have add/remove, on singleselect we have select/deselect. 

![Zrzut ekranu 2021-01-11 095016](https://user-images.githubusercontent.com/12393718/104161122-957b2a00-53f2-11eb-8775-0d34bad01a7c.png)

**Comment by steinsebastian** [comment]
@luklus Concerning #4: You are right this is different on the wireframes for multi/single select. I've talked to Jutta, our Product Owner, and she said that it should be always "Remove".
Concerning #3 we need to involve @schuppell (Lukas). Lukas, could you please decide whether "Qty" should be above or left of the quantity control.

**Comment by luklus** [comment]
ok so 4. fixed

![Zrzut ekranu 2021-01-12 104844](https://user-images.githubusercontent.com/12393718/104298028-ca0ae680-54c3-11eb-9b2d-6e36674620b6.png)

**Comment by schuppell** [comment]
Answered via Slack.

**Comment by luklus** [comment]
i prepare pr with this 3 fixes. Issue with label position remove on other ticket when everything will be confirmed

**Comment by Uli-Tiger** [comment]
Current State
1. fixed
2. fixed
3. **Text 'Qty' still displayed above quantity stepper instead of left of it.**

example: 
![image](https://user-images.githubusercontent.com/53090888/104756342-f9d41b80-575b-11eb-90d1-4ad69f2e6d83.png)

**Comment by luklus** [comment]
3. Fixed, example:

![Zrzut ekranu 2021-01-18 085840](https://user-images.githubusercontent.com/12393718/104887384-74bf5100-596b-11eb-9dfa-59b1e57f3b5e.png)
