### ISSUE TITLE
Issues with input field

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#10847]
There are some issues with attributes with input field:

1) Next button does not work after entering sth in input field

Product: CONF_LAPTOP
-> Click on Next button
  => works
-> In group CONF_LAPTOP_ACC go to attribute "Choose Engraving"
-> Enter something in the input field and immediately click on next button
  => Does not work. Group is not changed.
(If you wait for some seconds after entering sth in the input field it works)

Remark: in variant config UI there is also an issue with clicking next directly from an input field but the behavior is different (there the UI jumps to the top).

2) Value change of input field lost

Product: CONF_LAPTOP
-> go to group CONF_LAPTOP_ACC
-> enter a value for attribute "Choose Engraving"
-> click on checkbox "display port" of attribute "Laptop Connections"
-> change value for attribute "Choose Engraving" and immediately increase qty for value "Display port"
=> Value of "Choose Engraving" is changed back to old value

(Maybe same issue as with clicking on next group)

**Comment by Uli-Tiger** [comment]
**Root Cause**
As of today we react on the onChange even of the input field. This is only triggered if you press enter or when the focus of field is lost, typically because you click another UI-Element. In later case, when we click an element that will also cause an immediate action, we are likely to run into the situation that both actions overlap in time as they are fire almost simultaneously. This is  something which doesn't work for the reasons given below. This can happen in this 3 constellations:

1. input + group navigation: prev/next
What happens here is that the input change will trigger a PATCH request followed by a GET(actual group). While this running another get for the prev/next group is triggered. However er explicitly filter such actions in Configurator-Basic-Effects.ts, line 308. `filter((hasPendingChanges) => hasPendingChanges === false)`. So the group navigation is not executed.
Please note that the behavior is not guaranteed. It works as expected in rare cases, because this depends on the exact timings, which are not predictable.

2. input + click checkbox/radioButton
Almost the same as described above will happen. Both PATCH requests are send, but the second GET is filtered. This means that both changes are applied, but since the first GET will only contain the change of the first PATCH, the second change is not visualized on the UI. If you refresh the group, you can see that the change was indeed applied.
Please note that the behavior is not guaranteed. It works as expected in rare cases, because this depends on the exact timings, which are not predictable.

3. input + stepper
In this case the update from the stepper does not reach the redux state handling at all. An event is never sent. The reason for this is the debounce time of the stepper. The stepper does not sent an event immediately, instead it use a debounce pipe to wait for more changes and only sent the last state after the debounce time expires. Default is 500ms. However within 500ms the PATCH and GET requests for the input field will already be finished, consequently the stepper control was already destroyed and re-created, as we always re-render the page. However as part of destroying we unsubscribe from the quantity change which is currently in debounce phase, hence the event is never emitted.

**FIX**
To fix all three categories we need to change the input control behaviour. Instead of emitting the change onChange almost concurrently with the click on another UI element, we should emit the event when the user stops typing. This can be done using the same debounce behavior as for the stepper applied to any input change.
So the input PATCH would already fired before the user clicks another UI-Element.

**Comment by Uli-Tiger** [comment]
was decided to fix this directly in CPQ branch to evaluate it and later cherry pick to develop to also fix CPS
