### ISSUE TITLE
Fix styles in unit tree

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#11011]
Just observed that unit tree styles has been changed. I don't see any new changes in organization which could affect for that indent
![image](https://user-images.githubusercontent.com/8040837/106944576-0af2c580-6727-11eb-89c7-75bc76327744.png)
in theory it could be fixed by change below:
![image](https://user-images.githubusercontent.com/8040837/106944901-72a91080-6727-11eb-97c1-bc3f0561b6da.png)
but I'm not fan of that solution, let's find the reason first.

Second problem is that used icons have and differt width (8px vs 10px)
![image](https://user-images.githubusercontent.com/8040837/106945866-a6d10100-6728-11eb-917b-8c9be70f94c6.png)
It causes ugly effect (text-jumping) while toggling unit

**Comment by wangzixi-diablo** [comment]
Hi Buddy,

for the first issue, could you please kindly tell me that in which server you have made that screenshot?

I have tested using both dev2 and devci767 server in develop branch, and could not reproduce the issue mentioned in your screenshot. During my test, **margin-inline-start: -40px** works perfect:

<img width="786" alt="clipboard" src="https://user-images.githubusercontent.com/58975336/108674615-8a063d00-7520-11eb-87a7-0b8b69810687.png">

Best Regards,
Jerry

**Comment by wangzixi-diablo** [comment]
Hi Buddy,

For the second issue, here below is my analysis result.

The width difference for cx-icon.cx-icon.fas.fa-angle-down::before and cx-icon.cx-icon.fas.fa-angle-right::before is caused by the different inline-size of icon type CARET_RIGHT and CARET_DOWN. 

The value of inline-size is calculated by browser, instead of specified via CSS in our code. They may vary from difference devices ( different screen size ? ), for example in your screenshot, the pair of width is 8px VS 10px, while in my laptop, they're 12px VS 15px. 

And I have made an experiment: to change both icon_type to CARET_RIGHT, after that for sure, since now two icon has exactly the same type and then the same width, no text jumping anymore.

<img width="613" alt="2" src="https://user-images.githubusercontent.com/58975336/108679617-c6896700-7527-11eb-9ebb-fe0075eeb144.png">

Based on my analysis so far, I am thinking about introducing some CSS attributes to ensure that both CARET_DOWN and CARET_RIGHT has the same inline-size. 

Do you agree with me?

Best Regards,
Jerry

**Comment by Pucek9** [comment]
> Hi Buddy,
> 
> for the first issue, could you please kindly tell me that in which server you have made that screenshot?
> 
> I have tested using both dev2 and devci767 server in develop branch, and could not reproduce the issue mentioned in your screenshot. During my test, **margin-inline-start: -40px** works perfect:
> 
> <img alt="clipboard" width="786" src="https://user-images.githubusercontent.com/58975336/108674615-8a063d00-7520-11eb-87a7-0b8b69810687.png">
> 
> Best Regards,
> Jerry

That's really interesting. I was working on dev0 but I didn't even expect it to be the server's fault.
Ok, my observation on dev2 is still the same:
![image](https://user-images.githubusercontent.com/8040837/108702148-258bb380-7509-11eb-8c7e-427c49c089fe.png)
Windows 10. Chrome 88.0.4324.182 
The same for firefox and edge

![Screenshot_20210222-123516](https://user-images.githubusercontent.com/8040837/108703194-92ec1400-750a-11eb-91b4-7fe740656092.png)
Also the same on chrome Android 8.1

**Comment by Pucek9** [comment]
> Hi Buddy,
> 
> For the second issue, here below is my analysis result.
> 
> The width difference for cx-icon.cx-icon.fas.fa-angle-down::before and cx-icon.cx-icon.fas.fa-angle-right::before is caused by the different inline-size of icon type CARET_RIGHT and CARET_DOWN.
> 
> The value of inline-size is calculated by browser, instead of specified via CSS in our code. They may vary from difference devices ( different screen size ? ), for example in your screenshot, the pair of width is 8px VS 10px, while in my laptop, they're 12px VS 15px.
> 
> And I have made an experiment: to change both icon_type to CARET_RIGHT, after that for sure, since now two icon has exactly the same type and then the same width, no text jumping anymore.
> 
> <img alt="2" width="613" src="https://user-images.githubusercontent.com/58975336/108679617-c6896700-7527-11eb-9ebb-fe0075eeb144.png">
> 
> Based on my analysis so far, I am thinking about introducing some CSS attributes to ensure that both CARET_DOWN and CARET_RIGHT has the same inline-size.
> 
> Do you agree with me?
> 
> Best Regards,
> Jerry

Do you mean something like add style to icon in toggle-link-component like max-width? 
Just prepare your proposal, verify on few devices / configuration and show me 😁
