### ISSUE TITLE
PM2 max restart memory limit

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#11036]
> We have an urgent issue that affects production js storefront applications. The nodes are constantly throwing 502 exception due to the following reason;
> 
> 
> PM2 log: [PM2][WORKER] Process 1 restarted because it exceeds --max-memory-restart value (current_memory=1374523392 max_memory_limit=1288699904 [octets])
> 
> We are rendering with SSR, as far as I understand from the log statement, PM2 restart itself at 1.2G memory limit.
> 
> Can we please raise this value to the a maximum or infinite value immediately?

More details: https://sap.service-now.com/now/workspace/agent/record/sn_customerservice_case/ef795ef0db2d20d0240ca386059619b4

**Comment by LTiger14** [comment]
One note about this, if the customer is using 3.0 > (I think this feature is 3.0) it's possible to configure the optimization for SSR.

I don't think the SNOW thread mentions the customer Spartacus version. It might be worth it to get that information given the SSR optimization configurations could be useful in reducing the memory usage.

**Comment by Pucek9** [comment]
Thanks @LTiger14, already talked with Stan and we I'm waiting for possibility to ask question in SNOW.

**Comment by wangzixi-diablo** [comment]
We have another customer SNOW ticket complaining about the same issue:

https://sap.service-now.com/now/workspace/agent/record/sn_customerservice_case/efa9aee1db2fa4543a0183840596198d

They are using Spartacus 2.

**Comment by dunqan** [comment]
Most probably this is not a Spartacus issue, but a deployment one. SSR service will restart when the specified memory threshold will be exceeded, to avoid making it unresponsive. 

The possible solutions are:
- increase memory pod for SSR engine
- fix memory leaks
- use the SSR Optimization feature in Spartacus 3.x, to reduce SSR service load.

If, by any chance, the above is caused by a memory leak from core Spartacus, please provide a reproducible example, and we will reopen this.
