### ISSUE TITLE
Check Save Carts Works with Configurable Products

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11046]
TBD

**Comment by dydome** [comment]
Summary after testing:
1) Configurable product is possible to add to cart which will be next saved. It looks properly in saved carts details with configuration info:
![image](https://user-images.githubusercontent.com/18736434/112132164-9981b000-8bca-11eb-925f-c72d5c3f0a4d.png)

2) Unfortunately, there is a button "Edit Configuration" which doesn't work for saved carts. Once somebody clicks on it there is 400 status error in API with reason `{
   "errors" : [ {
      "message" : "Cart entry #0 does not exist",
      "type" : "CommerceCartModificationError"
   } ]
}`

![image](https://user-images.githubusercontent.com/18736434/112132416-e36a9600-8bca-11eb-9b8e-e9ebd60c5621.png)


3) Look like on saved cart details we should hide this button and allow the user to config the product directly in the cart.

**Comment by Platonn** [comment]
I suggest to solve the problem in 2 phases. But @Xymmer should decide at the end.
1. unblock the release
   I suggest to document that configurable products are not fully supported in the saved carts (the `Edit configuration` button is not working).

2. solving the issue later
   Hiding the button specifically in saved carts would require adding conditional logic. Please note that the button appears now:
      - in the added to cart modal (as `Edit configuration`)
      - in the cart details entries (as `Edit configuration`)
      - in order confirmation (as `Display configuration`)
      - in order history details (as `Display configuration`)

      Ideally product configuration should feature not know about the configurable products feature.
      And ideally configurable products feature should not know about the saved carts feature.
      We need to think about a proper solution...

**Comment by ChristophHi** [comment]
Saved carts do support product configurators from the business process point of view, the support is built into the accelerator UI as well. 
The only piece missing are the OCC APIs to load a saved cart entries configuration handle, and to update the saved cart. We wanted to build this in 21.05, but this got delayed because of the CPQ release => will be done in a 21.05 patch. Then small enhancements on SPA side (feature lib product-configurator) are needed to introduce new configuration owner types and routes.

So I agree to @Platonn 's comment: Let's first document the gap, and then later fix it when the OCC API's are available.
@JayEmKay-8 FYI

**Comment by bgambocjaviniar** [comment]
closing 

hotfix done in https://github.com/SAP/spartacus/pull/11649
