### ISSUE TITLE
Site theming

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11069]
Do the prerequisite for `theme` from https://github.com/SAP/spartacus/issues/11040

Create a mechanism that sets the CSS classs `cx-theme--<THEME_NAME>` in the main Angular's boostrapped component

**Comment by WeizhengSap** [comment]
Sample data PR is here: https://github.tools.sap/cx-commerce/spartacussampledata/pull/162

**Comment by WeizhengSap** [comment]
To QA: 
1. Since there are some sample data changes, system initialization is required. After initialization, you should be able to see 2 themes (sparta and blue) in `electronics-spa`, or other spa sites.
![Screen Shot 2021-02-18 at 9 33 26 AM](https://user-images.githubusercontent.com/44440575/108373589-11c11400-71ce-11eb-9ca6-e554e32d8125.png)

2. In spartacus, comment out `context`.
![Screen Shot 2021-02-18 at 9 58 31 AM](https://user-images.githubusercontent.com/44440575/108375366-dfb0b180-71cf-11eb-9ffe-d663b3ee7b92.png)

3. You should be able to see `sparta` in `<cx-storefront>` class.
![Screen Shot 2021-02-18 at 9 59 09 AM](https://user-images.githubusercontent.com/44440575/108375483-ffe07080-71cf-11eb-8462-2bad2cbc4646.png)

4. change theme to `blue` in backoffice; `blue` is in`<cx-storefront>` class.
