### ISSUE TITLE
bot detection

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#1108]

**Comment by tobi-or-not-tobi** [comment]
Since we have potential adaptive layout configurations, SSR output might be different per breakpoint. Whenever the SSR process or the edge cache layers are not able to address the client device, the process should decide on the preferred breakpoint. At the one hand, the mode where all content is rendered is preferred for search engines (typically the desktop version). But for an optimised mobile experience, the performance can be boosted by exposing the mobile optimised version. 

In this ticket we should collect knowledge around the following:
- evaluate wether we can render SSR based on client device type (if any)
- evaluate whether we can cache in varnish based on device type
- evaluate whether we can cache on the CDN based on device type

**Comment by tobi-or-not-tobi** [comment]
closing in favour of #9086
