### ISSUE TITLE
Different Order of Slots in Product Configuration. Firefox vs Chrome

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11256]
**Setup:** 
Chrome: 88.0.4324.182
Firefox:  v85.0

**Steps to Reproduce:** 
1. Navigate to Spartacus B2C storefront with Firefox
1.a. Use CCV2 instance https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD
2. Search for Home Theatre product.
3. Click on configuration button.
4. Select Room size and Colour of Home Theatre
5. Click on Add to Cart. 
6. Repeat steps 1 - 5 with Chrome

**Expected Results:** 
6. Same order of content slots is shown in Overview page.

**Actual Results:** 
6. Minor inconsistencies seen. 
6.a. Firefox:  Video System, Audio System. No General section slot 
6.b. Chrome: General, Video System. No Audio system section slot.

**Comment by giancorderoortiz** [comment]
Firefox: 

![Screen Shot 2021-02-24 at 7 28 23 AM](https://user-images.githubusercontent.com/46171897/109001192-a5815d00-7672-11eb-990a-ca09cf5c07c4.png)

**Comment by giancorderoortiz** [comment]
Chrome: 

![Screen Shot 2021-02-24 at 7 28 35 AM](https://user-images.githubusercontent.com/46171897/109001308-c8137600-7672-11eb-9519-a04d89dff17e.png)

**Comment by ChristophHi** [comment]
Hi @giancorderoortiz, there are 2 issues here (both _not_ connected to browsers if I see correctly).
First one is the wrong position of prev/next buttons which should be fixed after a re-deploy. See #11266 .
On the other hand, our configurator mock implementation is not multi-node enabled (only used for demo and CI purposes). Therefore SPA needs to address the same ccv2 node on each browser interaction. Please change the setup according to #7104 :
On SPA side, have backend.occ.useWithCredentials set to true.
On commerce side, ensure property corsfilter.commercewebservices.allowCredentials = true

**Comment by ChristophHi** [comment]
If you still face issues after these configuration changes, let me know!

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
@giancorderoortiz, it was fixed. Please, retest

**Comment by ChristophHi** [comment]
Order of contents slots has been fixed with #11266.
Other issue: Due to missing session stickiness. See #7104.
Our mock configurator (which we use for testing here) requires sticky sessions.

Also for productive configurators, sticky sessions are highly recommended. Sessions being non-sticky will not result in errors, but in bad performance.
Please re-test on a system where session stickiness is deployed. Note that in the commerce backend, the respective setting can be
corsfilter.ycommercewebservices.allowCredentials = true
or
corsfilter.commercewebservices.allowCredentials = true
depending on which web service extension is used!
