### ISSUE TITLE
The lazy-loaded feature can influence the cms mapping for components not covered by it

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#11287]
If lazy loaded feature contains Cms mapping definition for a component but feature configuration is not listing this component as a part of this feature, the lazy loading of the feature should not affect cms mapping of this component.

**Comment by jovanapavlica** [comment]
Would it be possible to include this fix also in version 2.1 (more concretelly we are using version 2.1.4 in our project). 
Currently we are on the topic of improving performance by using lazy loading of modules and there is no plan in doing the upgrade in the nearest future to 3.2, so we would really benefit from it since we did override most of the OOTB CMS components.

Thanks in advance

**Comment by jovanapavlica** [comment]
Any news about this ticket ? @dunqan 
Is it possible to add the fix for 2.1?
