### ISSUE TITLE
Security Validation Saved Carts 3.2.0

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11318]
Perform security validation on saved carts functionality being released with 3.2.0

**Comment by bgambocjaviniar** [comment]
Due date March 24th (before release 3.2)
Branch: `epic/saved-carts`
backend sample branch: `feature/GH-11138-spa`
use dev3-azure if you need to test as it already has the backend sample branch deployed to it.

Feature only uses 3 endpoints from the saved cart controller as it uses existing endpoints from the cart controller, which are available through our cart services
![Screen Shot 2021-03-05 at 4 49 13 PM](https://user-images.githubusercontent.com/29099466/110177353-d419d900-7dd2-11eb-8023-38941764eb75.png)


### MVP 1

**Main cart page**

two new buttons above the cart details component
- Saved Carts
- [x] As anonymous user, it should redirect to login page
- [x] As logged in user, it should redirect to my-account/saved-carts page (history page) ---- the listing page can be accessed through the my-account dropdown as wel.
- Save Carts For Later
- [x] As anonymous user, it should redirect to login page
- [x] As logged in user, it should save the cart and create a new one (empty cart)
------> The save functionality calls the [PATCH] save endpoint from the save controller and re-uses existing services for carts to create a new cart

**Saved Cart Listing (history) page**
- loads the cart page using the load all carts endpoint from the carts controller, but we load all saved carts only
- View all relevant data that needs to be displayed
- Make cart active
- [x] if there are no carts as active, we make the saved cart as the new active cart and it will be displayed in the cart page
- [x] if there exist an active cart, we save the active cart and make the saved cart the new active cart. Basically swapping them.
----> uses the restore endpoint from saved cart controller

**Saved Cart Details page**
- loads single saved cart using the get saved cart endpoint from saved cart controller
- Make Cart active
- [x] same cases as the cart listing page
- Delete Saved Cart
- [x] delete the saved cart and redirects you to the listing page. (Do note it is not optimal as we need events to make it fully functional)
- Edit Saved cart (pencil icon)
- [x] can edit the name of the viewed saved cart
- [x] can edit the description of the viewed saved cart 

***** Note for the saved cart details page ****
the saved cart item list component is just a wrapper component which is literally the same one as what you can do in the cart page. The buttons are not working as of yet (Friday, March 5th) but it will soon. It's not a problem as it just updates the current saved cart with the appropriate cart items / entries
For example, as shown in the screenshot below.
![Screen Shot 2021-03-05 at 5 03 47 PM](https://user-images.githubusercontent.com/29099466/110178661-c8c7ad00-7dd4-11eb-81f2-03e16f1da65c.png)

-------------

**MVP 2** (not started)
- Everything from MVP 1

**Saved Cart Details page**
- checkboxes in the saved cart items list component
- [x] can add single product to active cart
- [x] can add all products to active cart
-----> functionality will be similar to wishlist, however we can do multiple addition of products to the active cart instead of one.

**Comment by giancorderoortiz** [comment]
Security review completed. 
Good job :-)
