### ISSUE TITLE
After updating email and login user is redirected to update email page

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#11347]
**Current behavior**
Currently when you change email you are logged out and redirected to login. After login you are redirected once again to update email page.

**Expected behavior**
After login you are redirected to home page

Related to #9638

**Comment by marlass** [comment]
Solution idea:
- expose `setRedirectUrl` (make it public + add unit tests) in `AuthRedirectService`
- use that method in component before we logout user

**Comment by Platonn** [comment]
To avoid feature components needing to inject the AuthRedirectService (just to call AuthRedirectService.setRedirectUrl()), we might consider passing the redirect url via a query param of the /login route. This is a common pattern used in web applications btw.

Then the update email component would need to only pass the query param:
```typescript
routingService.go(
  { cxRoute: 'login'},
  { queryParams: { redirectUrl: routingService.getUrl({cxRoute: 'home'}) } }
) 
```

Then the LoginGuard should intercept the query param and save it in the AuthRedirectService.setRedirectUrl. (This would need to be implemented.)

**Comment by Platonn** [comment]
To avoid feature components needing to inject the `AuthRedirectService` (just to call `AuthRedirectService.setRedirectUrl()`), we might consider passing the redirect url via a query param of the `/login route. This is a common pattern used in web applications btw.

Then the update email component would need to only pass the query param:
```typescript
routingService.go(
  { cxRoute: 'login'},
  { queryParams: { redirectTo: routingService.getUrl({cxRoute: 'home'}) } }
) 

// /login?redirectTo=<uri-encoded-homepage-url>
```

Then the `LoginGuard` should intercept the query param and save it in the `AuthRedirectService.setRedirectUrl`.

**Comment by Platonn** [comment]
After discussion with Stan, we decided to go for the simple solution with calling explicitly `AuthRedirectService.setRedirectUrl.` as Marcin proposed [above](https://github.com/SAP/spartacus/issues/11347#issuecomment-861455602)

Why we don't want query param:
- it's not needed _per se_ (it was needed only in old multi-page apps)
- we expose internal logic in the URL (the URL is more ugly, moreover the the URL can be prepared by users in strange ways i.e. `?redirectTo=strange/page`), but there are no clear advantages of it

We considered also using [`{ state: ... }` property](https://angular.io/api/router/NavigationBehaviorOptions#state) instead of query params -> then the redirect url would land in the `history.state` (history API)
But we don't want it, because this redirect URL remains in the history record's state. When the user comes back in his browser to this old login page (i.e. by expanding dropdown with the list of past pages in his browser) and he logs in, then we navigate him to the redirect url, which was specified far in the past.

Moreover, both above solutions have the drawback that we implement the feature using a generic angular API (weakly typed objects inside `NavigationExtras`: .queryParams, .state).

We don't know other alternative solutions.

That's why we'd like to use `AuthRedirectService.setRedirectUrl` explicitly in the components. The drawback is injecting new dependency to the component's constructor. But being explicit can be considered an advantage in this case. So it's not so bad as I thought at the beginning.

**Comment by bgambocjaviniar** [comment]
Just want to point out, but it was already taken

Wouldn't `clearRedirectUrl` suffice for this case from `auth-redirect.service.ts`?
Reason being is when we login, we call the `redirect` method from `auth-redirect.service.ts` using `loginWithCredentials`, in which if it is undefined, it 'redirects' to the homepage by default.

**Comment by Platonn** [comment]
@bgambocjaviniar correct, the result will be the same when clearing. 

But I'm not in favor in clearing. Using clearing method in the UI component requires additional knowledge about the implementation detail of the AuthRedirectService -> that undefined redirect url will fallback to '/'. 

IMHO it looks more natural to set a explicitly the redirect url to the homepage.

**Comment by giancorderoortiz** [comment]
I don't see a fix yet. 
Deployed latest develop branch here: 
http://spartacus-devci7673.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/

**Comment by giancorderoortiz** [comment]
<img width="1783" alt="Screen Shot 2021-06-29 at 4 06 07 PM" src="https://user-images.githubusercontent.com/46171897/123860937-8f233080-d8f4-11eb-913b-daeba4606ed4.png">

**Comment by giancorderoortiz** [comment]
Error in previous deployment. 
After retest, I see a fix.  Redirects to homepage, not update-email page. 

![Screen Shot 2021-06-30 at 11 16 43 AM](https://user-images.githubusercontent.com/46171897/123986910-b9c4c600-d994-11eb-9189-a89261e7824f.png)
