### ISSUE TITLE
ASM launch config  doesn't have custom outlet

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#11372]
I have custom selector for storefront. It is named of `sd-storefront`. And asm component doesn't work because I can't change this config https://github.com/SAP/spartacus/blob/c012041cc02c6cfbe703e468f4d62b284b913fde/projects/storefrontlib/src/cms-components/asm/default-asm-layout.config.ts#L7

![image](https://user-images.githubusercontent.com/17045072/109946301-241c7100-7ce9-11eb-930b-a1a67b9853eb.png)

- Library version: 3.1.0

**Comment by giancorderoortiz** [comment]
@plabadie fyi

**Comment by bgambocjaviniar** [comment]
@alvteren 

1- Can you provide more information on what you're trying to do? 

2- I'm assuming you want us to make the outlet customizable, so that it's not fixed on cx-storefront outlet ref. But I'm wondering about what are you trying to achieve and how are you using this config. From what you mentioned about creating a custom storefront selector, I'm assuming everything you have within your own customized storefront component are customized, so can't you just point to your own outlet.

3- Looking at 3.1 releases, I see that the AsmMainUiComponent is not exported. Were you asking to export it instead?

------
I will provide a PR for that customizable outlet, but I think your case may be different if you have your own customized storefront component

**Comment by alvteren** [comment]
I mean, I doesn't have selector `cx-storefront` on my app. Instead the selector I have `sd-storefront` and that Asm Component isn't working

**Comment by bgambocjaviniar** [comment]
PR: GH-12767


QA:

- enable asm by appending `?asm=true` to the url
- in your app.module, you can override the custom outlet 
```
(StorefrontOutlets as any)['STOREFRONT'] = 'abc';
```
- in your app.module as well, you can override the value for the outlet 
```
    provideConfig(<LayoutConfig>(<unknown>{
      launch: {
        ASM: {
          outlet: 'abc',
        },
      },
    })),
```

- verify asm is enabled when oulets matches

--------
3.4.x maintenance branch: GH-12847

**Comment by Platonn** [comment]
@alvteren, did you try simply referencing an existing main outlet name `"cx-storefront"` inside your custom SdStorefrontComponent?
```html
// the html template of your custom SdStorefrontComponent:
<ng-template [cxOutlet]="'cx-storefront'" cxPageTemplateStyle>
   ...
</ng-template>
``` 

Then the ASM plugin should insert itself above the outlet OOTB.

### Explanation
The outlet names are just abstract string (unique) names, and they are not tightly connected to any components' selectors. By "coincidence" the outlet name `"cx-storefront"` used inside the OOTB StorefrontComponent looks the same like the component's selector `<cx-storefront>`. **I understand, this might be confusing.** However, if we only wanted so, we could have named the outlet inside StorefrontComponent: `"funky-main-outlet"`.

Therefore, you should be able to reference this original outlet name `"cx-storefront"` in your custom SdStorefrontComponent, regardless its selector is `<sd-storefront>`

Please let me know in the case of questions.

---

cc @bgambocjaviniar @hackergil
