### ISSUE TITLE
Missing environment variables break the prod SSR render

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11426]
**Describe the bug**
When running SSR in prod mode, the app is not working. the environment variables (including occ baseUrl) are empty, which causes SSR App not working.
This likely is our internal setup issue. Not a problem that affects customers.

**Tell us the version of Spartacus**
latest develop (6a94f352e18d51208c5db7be269b91aadf7a41f4)

**To Reproduce**
1. build SSR application in prod mode
   ```bash
   yarn build:libs
   yarn build
   yarn build:ssr
   yarn serve:ssr:dev
   ```
2. in another terminal run `curl localhost:4000` (port of SSR prod)
3. The app is not working and the error is throwed in SSR console

**Expected behavior**
The app in SSR prod mode works.

**Screenshots**
- error in console
   ![image](https://user-images.githubusercontent.com/4001059/110444516-695fea80-80bd-11eb-9216-b6a941c40b93.png)
- undefined baseUrl in SSR (console.log config in SSR):
   ![image](https://user-images.githubusercontent.com/4001059/110445069-0c186900-80be-11eb-9e95-620dfe39bc66.png)
- empty `buildProcess.env` (prettified source of `dist/storefrontapp-server/main.js` vs. original `environment.prod.ts`):
   ![image](https://user-images.githubusercontent.com/4001059/110444859-cb205480-80bd-11eb-80e0-bfb3e8befac4.png)
   ![image](https://user-images.githubusercontent.com/4001059/110445766-be503080-80be-11eb-9f80-a9229415d0c7.png)

**Additional context**
Likely the issue occurs becasue in prod SSR the `buildProcess.env` is empty.

**Comment by KateChuen** [comment]
Tested locally.
- cloned the develop branch of spartacus
- had to remove the node_modules and run yarn first, otherwise i was getting some errors
- then ran the commands described in the ticket

All good. App in ssr works. 
Only thing is i see these when i load the app in ssr (confirmed with Gil that these can be ignored) :
![Screen Shot 2021-11-15 at 3 36 55 PM](https://user-images.githubusercontent.com/45409515/141850439-7a8df9a8-191a-4a6f-9df3-f934954b915a.png)
