### ISSUE TITLE
Saved Cart UI styling update

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#11438]
Update UI for the saved cart listing and details pages to match wire and visual mock ups.

**Comment by bgambocjaviniar** [comment]
Reminder: @morganm58 

details page
- overview and actions component are fine as is as discussed with Anthony due to normalizing how 'details' page looks like until further notice
 
listing (history) page:
- I believe the requirements says to omit the blue colors (name and actions columns)

cart page:
- fix extra padding that exist when there exist only 1 product
- do not forget the component placement will not be under the header* (only the fix in relation to the padding needs to be fixed)

**Comment by bgambocjaviniar** [comment]
PR: GH-11504
