### ISSUE TITLE
[Medium] Home Theatre: Inconsistent display of caret for video system group

### ISSUE THREAD

**Issue by JayEmKay-8** [SAP/spartacus#11627]
http://cpqteamserver.mo.sap.corp:4200/electronics-spa/en/USD/configure/vc/product/entityKey/CONF_HOME_THEATER_ML

Configure Product 'Home Theater System'
For two different room sizes, although projector type is 'no projector' in both cases, for one room size the caret for 'video system' is shown (indicating that there are levels below), for the other room size the caret for 'video system' is **not** shown.
Expectation: Caret should be shown in both cases.

Room size: 41-60 sqm
**Video system has no caret**
Projector type: no projector

Caret appears for video system if I choose Projector type: Liquid Crystal Display

Room size: 25-40 sqm
**Video system has caret**
Even though projector type: no projector

Caret appears for video system if I choose Projector type: Liquid Crystal Display
[2021-03-23_no-caret-for-video-system.pdf](https://github.com/SAP/spartacus/files/6188959/2021-03-23_no-caret-for-video-system.pdf)

**Comment by ChristophHi** [comment]
Hi @JayEmKay-8 , I feel this is ok. Because if you select
- `41-60 sqm`, the `Video System` group has only one sub group, therefore the intermediate group level is removed, caret is not shown, as click on `Video System` group directly takes you the attribute selection
- `25-40 sqm`, the `Video System` group has 2 sub groups => caret is shown.

Let me know if you disagree!

**Comment by JayEmKay-8** [comment]
You're totally right. Sorry I opened this ticket unnecessarily.
