### ISSUE TITLE
Mobile sign in improvement (design, define, execute) #1512

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#1170]
From Tobias: 
design concern: no indication of logged in user on mobile, until you click the hamburger menu

**Comment by Xymmer** [comment]
This is what i see in Chrome, is it a browser-specific issue? it says "Hi Bil Marcotte"
Or do you mean that there is no indication that you are signed in until you click the menu?
![img_606c2c1b1bc3-1](https://user-images.githubusercontent.com/4998145/52212202-f474b380-2859-11e9-9a4b-5ef25544b68f.jpeg)

**Comment by tobi-or-not-tobi** [comment]
"there is no indication that you are signed in until you click the menu" – exactly. Would be great to see a "user" icon or something similar in the bar.

**Comment by vekterdude** [comment]
Please change this request to a "Won't do" for the following reasons:
This project is rapid retail and rapid retail does not prioritize signed in status visible on mobile header, since phones and tablets are personal, not used in internet cafe's, libraries or public places (ie. if the user signs out or not it is not particularly important) A brief polling of random sites revealed this distribution of the feature:
Aritzia: No
Amazon: Yes
LLbean.com: No
Tedbaker.com: No
Home Depot.com: No
Walmart.com: No
Dyson.com: No
Harrods.co.uk: No
boots.com: No

So, only Amazon has this status exposed on the mobile header, and amazon is NOT rapid retail.

In addition, we are saving that space (what little there is of it in the mobile / tablet header) for a find a store / shop this store feature in the semi-near future.

Hope this helps,
Anthony

**Comment by mszczepaniak** [comment]
won't do

**Comment by Xymmer** [comment]
reopening as there is some value in having this
