### ISSUE TITLE
Customer credentials can login into ASM mode. 

### ISSUE THREAD

**Issue by OmarZaki** [SAP/spartacus#11816]
**Describe the bug**
Customer credentials can login into ASM mode. 

**Tell us the version of Spartacus**
- Library version: [2.1]

**To Reproduce**
1. Open ASM mode. 
2. Use customer credentials to login. 
3. do login. 
Customer credentials can login but can't perform search or start customer emulation.

**Expected behavior**
Customer credentials should not be allowed to login to ASM mode, it should shows bad credentials error message. 

I have noticed that the effect CustomerSupportAgentTokenEffects which does load the token uses the same UserAuthenticationTokenService which is been used for customer login.

**Comment by giancorderoortiz** [comment]
@plabadie fyi

**Comment by plabadie** [comment]
In short, this is the Spartacus expected behaviour and not a bug.

While it might look like a customer can sign into ASM mode with his customer credentials, it is not the case under the hood.

OCC provides a single authentication endpoint and both the regular customer login form and the cs agent login form call this exact same authentication endpoint.  Also this unique authentication endpoint does not provide info about which kind of user is authenticated.    

There is no way we can technically prevent customer credentials to be used in the ASM UI, but should this happen, the customer is still signed in as a customer, and not as a cs agent. The backend knows about the user and his roles and will not allow a user to interact with the API in a way he is not allowed to.

It would likely provide a less confusing user experience if Spartacus could handle this case upfront instead of letting the non-agent user try to use the ASM ui and get errors, but within the boundaries of OCC, it is not possible.
