### ISSUE TITLE
ASM can't auth by customer

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#12026]
**Describe the bug**
ASM can't auth by customer

**Tell us the version of Spartacus**
- Library version: 3.2.0

**To Reproduce**
1. Open url with ?asm=true
2. Authorize by Customer Support Agent
3. Display message "Standard customer session in progress." 

**Expected behavior**
Display search input by customers
![image](https://user-images.githubusercontent.com/17045072/115240872-db016e80-a128-11eb-87ea-ae9711407a3c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17045072/115239566-90cbbd80-a127-11eb-848e-88ad8868efc8.png)

**Additional context**

I think It happens because in AsmMainUiComponent this.customer$ has empty object `{}` when I am authorized by Customer Support Agent.

```typescript
    this.customer$ = this.authService.isUserLoggedIn().pipe(
      switchMap((isLoggedIn) => {
        if (isLoggedIn) {
          this.handleCustomerSessionStartRedirection();
          return this.userService.get();
        } else {
          return of(undefined);
        }
      })
    );
``` 
If I has changed  from `this.userService.get();` to `this.userService.get().pipe(filter((details) => Boolean(Object.values(details).length)));` it fix the bug

Customer Support Agent credentials from localStorage
![image](https://user-images.githubusercontent.com/17045072/115240222-3121e200-a128-11eb-9c80-e74fc99f700c.png)

**Comment by psmul** [comment]
@alvteren would you mind providing more details on your case? 
Screenshots and approach presented correspond rather to the 2.x version of functionality. In 3.x this behaviour was changed so you won't be able to see such a message because the customer session will be changed to an emulation session when the agent signs in.

**Comment by alvteren** [comment]
This is exactly 3.2.0 version

![image](https://user-images.githubusercontent.com/17045072/122197990-66854a80-cea1-11eb-8dce-4d9deb02250d.png)

**Comment by psmul** [comment]
Yes, as mentioned above, the approach changed with 3.x release. Now user won't see this message anymore and the session will be automatically switched to emulation mode.

**Comment by alvteren** [comment]
I don't understand. Can't "support agent" to login by customer now?

**Comment by psmul** [comment]
In version 2.0 ASM worked in a way that ASM agent had to wait for user/customer to log out and end his session, hence the message "Standard customer session in progress".

In version 3.0 we changed the approach. You can no longer hold authentication for two users simultaneously. That's why when you're logging in as an ASM agent, you're being logged out on your standard customer session and will be able to start emulation mode with this user again. So there's no scenario for showing the desired message, as we're no longer (as ASM agent) blocked by customer active session.

**Comment by psmul** [comment]
I'm closing this issue for now as I think the problem was explained in the above comment. Please feel free to reach out if in doubt and I will reopen this ticket.
