### ISSUE TITLE
Update cart entry content type to work with 2105

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#12092]
**Changes are aimed for 3.3**

With 2105 some deprecated endpoints were removed. The behavior is still there and the URL remains the same, the only change is with the content type. Instead of `application/x-www-form-urlencoded` use `application/json`. The changes will be made in the existing adapters.

Endpoints that need to be updated:
- POST `/{cartId}/entries` -> `occ-cart-endtry.adapter -> add()` 
- PATH `/{cartId}/entries/{entryNumber}` -> `occ-cart-entry-adapter -> update()`

**Comment by KateChuen** [comment]
Tested on electronics storefront against 2105 (backend on dev9 server).
- Tested develop branch (frontend on dev9 server)
- Tested release/3.3.x branch (local because I couldn't get it work on dev9 server)

All good, now content-type is application/json for both 
- POST (adding to cart),
<img width="651" alt="Screen Shot 2021-09-21 at 9 42 15 AM" src="https://user-images.githubusercontent.com/45409515/134232988-d0964108-afb8-4701-a57b-f84bdce8f7e4.png">

-  and PATCH (updating a cart). 
<img width="652" alt="Screen Shot 2021-09-21 at 9 43 09 AM" src="https://user-images.githubusercontent.com/45409515/134233058-334da2f4-834a-4c0d-aa64-7ba41d52904d.png">
