### ISSUE TITLE
CPQ. Able to add Configurable Product With Cost Equal 0.00

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12240]
Environment:

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1. Navigate to B2B powertools that has CPQ enabled.
2. Login
3. Search for Coffee Machine (i.e. CONF_COFFEEMACHINE_3000).
4. click Add to Cart button at bottom of screen.

**Expected Results:** 
4.a Product is added to cart with no-configuration or with default configuration AND a default cost price > 0 per unit. 
4.b. If product cannot be added to cart, then an error message should be displayed, or the Add-To-Cart button should be disabled.

**Actual Results:** 
4.a Product is added to cart with item price = $0.00. 
4.b. It's then possible to checkout a CQP product with cost = $0.00

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/12208

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/12218

**Comment by giancorderoortiz** [comment]
Add to Cart Dialogue: 

![Screen Shot 2021-04-30 at 4 18 23 PM](https://user-images.githubusercontent.com/46171897/116756084-8045fd80-a9d9-11eb-8a64-a44a009e6ab2.png)

--- 
Checkout steps: 

![Screen Shot 2021-04-30 at 4 14 53 PM](https://user-images.githubusercontent.com/46171897/116756170-ab305180-a9d9-11eb-99a1-693637dac739.png)
![Screen Shot 2021-04-30 at 4 15 18 PM](https://user-images.githubusercontent.com/46171897/116756181-ae2b4200-a9d9-11eb-98d7-8aee06a36866.png)
![Screen Shot 2021-04-30 at 4 15 46 PM](https://user-images.githubusercontent.com/46171897/116756198-b4212300-a9d9-11eb-8d0b-0ce2f5a94309.png)
![Screen Shot 2021-04-30 at 8 22 21 AM](https://user-images.githubusercontent.com/46171897/116756211-ba170400-a9d9-11eb-9931-23c93a594f31.png)

**Comment by ChristophHi** [comment]
That's a twofold issue: 
(1) Able to checkout an incomplete configuration: Addressed with #11902. In the meantime, we document how customers need to implemented the check on their own (see https://sap.github.io/spartacus-docs/configurable-products-integration/#configuring-spartacus-for-cart-validation)
(2) Price being zero: This is a pure modeling issue. In this CPQ tenant, the coffe machine has price zero for the org data we are using. Commerce per default does not prevent submitting such an order => This is not SPA related, we don't even want to introduce checks for that, because the commerce backend should drive the business logic (customers could introduce checks on commerce side that would prevent carts from being ordered in that case). Hence closing that ticket
