### ISSUE TITLE
Sync cart from Accelerator to Spartacus 

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#12286]
As part of #11682 we like to support synchronising the cart token from Accelerator to Spartacus and visa versa, both for anonymous and logged in users. 

When a new cart is created in the Accelerator (as in using the POST `/cart/add` resource), the server response contains a cookie to be set in the browser with the key in the format of `${site.uid}-cart`, and the value as cart `GUID`. For example: `electronics-cart=08063b11-c935-4ecb-bcdb-7c4e46501249`. 

An important limitation to access this cookie client side is that the cookie is set to _HTTP-only_, which means that Spartacus cannot read it. The access control should be set to NOT HTTP-only to allow access from Javascript. Moreover, it is recommended to do this a reasonable time before launching the Spartacus pages that need to access the cookie.

Spartacus should be able to read/write from the Accelerator cookie, so that it is synchronised.

**Comment by tobi-or-not-tobi** [comment]
@LTiger14 can you validate whether this is already possible with the changes you were planning on in the `StatePersistenceService`?

**Comment by LTiger14** [comment]
One thing to note with regards to the cart in Spartacus vs Accelerator.

- In **Spartacus** the cart `GUID` is user for anonymous users and the cart `code` is used for authenticated users. This is the case because OCC requirements.
- In **Accelerator** the cart `GUID` is always used.

For this work we will assume that no changes in OCC or Accelerator will happen. **The discrepancy will be handled on the Spartacus side.**

- The cookie will always contain the `GUID` and Spartacus will make it work by using the `GUID` to pull the cart `code` for authenticated users.

**Comment by LTiger14** [comment]
Replaced with #12511
