### ISSUE TITLE
Test fails when run against 2105

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#12519]
See https://dashboard.cypress.io/projects/k3nmep/runs/15178/overview
Would be good to get an explanation I can forward, but would also like these fixed

**Comment by LTiger14** [comment]
The 6 failures detected were  in two different tests, Checkout and Guest Checkout.

All of the errors were caused by the hard coded shipping price. In the tests the values were hard coded to `11.99` while in OOTB 2105 the price is `9.99`.

Changing the `11.99` value to `9.99` fixed the broken tests.

**Comment by hackergil** [comment]
Please remove the hardcoded price. We should not rely on hardcoded values

**Comment by LTiger14** [comment]
Green ✅ https://dashboard.cypress.io/projects/k3nmep/runs/15197/overview
