### ISSUE TITLE
TUA-SPA Storefront: Not able to load storefront when upgrading spartacus form 3.0.0 to 3.3.0

### ISSUE THREAD

**Issue by ketki-mujumdar** [SAP/spartacus#12632]
**Describe the bug**
Not able to load storefront when upgrading spartacus form 3.0.0 to 3.3.0

**Tell us the version of Spartacus**
Spartacus 3.3.0

**To Reproduce**
1. Update spartacus entries in package.json to latest 3.3.0
2. Yarn install
3. Yarn build
4. Yarn start

**Expected behavior**
Telco spa storefront should be rendered 

**Actual Result**
Getting blank page with error in console saying 'TypeError: Cannot read property 'location' of undefined'

**Screenshots**
![image](https://user-images.githubusercontent.com/79191673/120339223-8c8fe400-c312-11eb-9f7b-eebd472ddf56.png)

<img width="718" alt="Screenshot 2021-06-01 at 4 55 37 PM" src="https://user-images.githubusercontent.com/79191673/120339815-1344c100-c313-11eb-8f81-a4270b5be002.png">

**Additional context**
Find discussion with @Platonn Krzysztof Platis here https://spartacus-storefront.slack.com/archives/CD16V16FR/p1622539518065900

**Comment by Platonn** [comment]
How to fix: replace static property ModalService.rootComponent with a getter that is evaluated lazy (not during the service instantiation), but only when #modal method is called.
```ts
protected get rootComponent() {
    return this.applicationRef?.components?.[0]?.location?.nativeElement;
  }
```

This issue didnt happen in the default spartacus, beacaue ModalService is instantiated lately after the page is rendered (and applicationRef has created the root component). But in case of the custom TUA storefront, I guess the ModalService is injected and instantiated much earlier (due to some customization), before the root component is instantiated.

Btw. when doing backport, we can add missing `?.` before `.location`.

Note: the bug was introduced since 3.3 (PR https://github.com/SAP/spartacus/pull/11918/files#diff-cbf43316e96240a3461f591b9482200e8b946aacdbb098afe4c6721152d78c16R34-R35)
