### ISSUE TITLE
ApproverGuard is not exported in the public api

### ISSUE THREAD

**Issue by e2yerik** [SAP/spartacus#12840]
**Describe the bug**
ApproverGuard is not exported in the public api. 

**Tell us the version of Spartacus**
- Library version: 3.2

**To Reproduce**
1. I want to override the OrderApprovalDetailShippingComponent 
2. I create provide a configuration for my implementation
```
providers: [
    provideConfig(
      {
        cmsComponents: {
          OrderApprovalDetailShippingComponent: {
            component: MyCustomOrderDetailShippingComponent,
            providers: [
              {
                provide: OrderDetailsService,
                useExisting: OrderApprovalDetailService,
              },
            ],
            guards: [AuthGuard, ApproverGuard],
          },
        },
      }),
  ]
```
3. I can import all dependencies except ApproverGuard

**Expected behavior**
I can import ApproverGuard from `@spartacus/core`

**Comment by giancorderoortiz** [comment]
@plabadie please double check if it's ok to export ApproverGuard.

**Comment by plabadie** [comment]
Since the `AuthGuard` is part of the public API I see no reasons not to expose `ApproverGuard `.  

Because `ApproverGuard` guard lives in `@spartacus/organization/order-approval`, the expected result for the ticket should be 
- I can import `ApproverGuard` from `@spartacus/organization/order-approval`

**Comment by KateChuen** [comment]
No QA required on this ticket.
