### ISSUE TITLE
`undefined` is send as an authorization token when handling expired token

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#13254]
Expired token handling routine sends `udefined` as an authorization token, which causes an error:

> WWW-Authenticate: Bearer realm="hybris", error="invalid_token", error_description="Invalid access token: undefined"

**Comment by wangzixi-diablo** [comment]
Just some of my thoughts.Kindly remove it if you think is not related to this issue.

for the token expire issue, currently Spartacus never checks an access token is expired, but simply add it to occ calls and react on server response accordingly.

This kind of token expire handling approach is documented as [here](https://stackoverflow.com/questions/30826726/how-to-identify-if-the-oauth-token-has-expired/30826806). 

Besides it there is alternative, since we have expires_in stored in local storage, on each occ API call, we can check the current time against the expire time in Spartacus and make a token refresh request before resource request if the access_token has expired. In this way, there would NOT be tons of 401 auth exception occurred in Commerce backend.
