### ISSUE TITLE
Spike: Handle dependencies with other libs

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#13284]
We need consider these files:
![Screen Shot 2021-07-28 at 4 34 02 PM](https://user-images.githubusercontent.com/44440575/127386434-51d7fca8-f976-43b6-b1f6-ca5beeb50013.png)

They import deprecated services, modules, components and normalizer tokens. We ignore the ones which import deprecated models.

**Comment by plabadie** [comment]
# Checkout Lib

- OrderOverviewModule + OrderOverviewComponent
- REPLENISHMENT_ORDER_NORMALIZER
- ORDER_NORMALIZER
- Model(ish)
  - ORDER_TYPE (enum from replenishment-order.model.ts)
  - Order
  - OrderEntry
  - recurrencePeriod (const from replenishment-order.model.ts)
  - DaysOfWeek (enum from replenishment-order.model.ts)
  - ScheduleReplenishmentForm (interface from replenishment-order.model.ts)
  - ReplenishmentOrder (interface)

# Organization

- OrderDetailTotalsComponent ( Used as a token, original implementation pulls OrderDetailsService )
- OrderDetailShippingComponent ( Used as a token, original implementation pulls OrderDetailsService ),
- OrderDetailItemsComponent, ( Used as a token, original implementation pulls OrderDetailsService ),
- OrderDetailsService (used directly and as an injection token)
- ORDER_NORMALIZER
- Model
  - Order

# Saved-Cart
Model
 - OrderEntry


# CPQ
Model
 - OrderEntry

# Strorefrontlib

- Cart "shared" components
  - Model
    - ConsignmentEntry

# Core

  - Model
    - Order
    - OrderEntry



- projects/core/src/model/cart.model.ts
  - Models
    - DeliveryMode
    - OrderEntry
    - PickupOrderEntryGroup
    - PromotionOrderEntryConsumed

- projects/core/src/occ/adapters/cart/converters/order-entry-promotions-service.ts

  - PromotionOrderEntryConsumed (model)

- user-occ-transitional.module.ts

  - ORDER_RETURN_REQUEST_NORMALIZER
  - UserOrderAdapter
  - UserReplenishmentOrderAdapter
  - OccReturnRequestNormalizer
  - OccUserOrderAdapter
  - OccUserReplenishmentOrderAdapter

- projects/core/src/occ/adapters/user/user-occ.module.ts

  - ORDER_RETURN_REQUEST_NORMALIZER
  - UserOrderAdapter
  - UserReplenishmentOrderAdapter
  - OccReturnRequestNormalizer
  - OccUserOrderAdapter
  - OccUserReplenishmentOrderAdapter

- projects/core/src/user/store/effects/transitional.ts

  - ConsignmentTrackingEffects
  - OrderDetailsEffect
  - OrderReturnRequestEffect
  - ReplenishmentOrderDetailsEffect
  - UserOrdersEffect
  - UserReplenishmentOrdersEffect

- projects/core/src/user/store/reducers/index
- projects/core/src/user/store/reducers/transitional.ts
  - registers many deprecated reducers

**Comment by plabadie** [comment]
The dependency issues listed above can be grouped into 5 categories:

# Dependency Issues with mitigations:

- [x]  Normalizers stay in core for now ( GH-13309 )
  - We will move them to libs in 5.0 ( GH-13321 )

- [x]  OrderOverviewComponent and OrderOverviewModule stay in core for now (GH-13322 )
  - We will move them to libs in 5.0 ( GH-13324)

- [x]  All Order models stay in core for now (GH-13325)
  - We will move them to libs in 5.0 (GH-13326)

- [x]  Organization Lib uses these components from storefrontlib:
  - OrderDetailTotalsComponent
  - OrderDetailShippingComponent
  - OrderDetailItemsComponent
    - For 4.x, we have to tolerate that when using Order Lib, the Order Approval feature still uses the order components from storefront lib.  We need to document that to explain this and avoid confusion.  (GH-13327)

- Also we discovered a fix to do in the next major for OrderDetailPermissionResultsComponent GH-13351
- [x]  Order related "core" code (facace + all ngrx store) can not be removed from the app while usiinf the order lib
  (because they are in existinig modules with other user related code that is not moved to order lib )
  -  Mitigation: we create new transitional modules: (GH-13328)

**Comment by plabadie** [comment]
Closing.  Spike done.  See conclusion above.
