### ISSUE TITLE
[Bill followup] Quick order: Misleading message when adding a non-purchasable item

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13567]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.84.65.98

**Steps to Reproduce**
Go to powertools storefront
Click on Quick Order
Add this SKU: 50500000
Press Enter
The item is listed
![Screen Shot 2021-08-30 at 11 03 22 AM](https://user-images.githubusercontent.com/45409515/131361632-078a3c0a-044a-459f-a1be-4e733bef7cb5.png)

Click "Add to Cart"
Get a successful message that item is added to cart.
![quickorder_nonpurchasable](https://user-images.githubusercontent.com/45409515/131361842-ac72ea71-106c-4fe4-a01f-3dd6d049e524.png)

**Actual Result**
Item is not added to cart. 
You get a 400 back. 
![Screen Shot 2021-08-30 at 11 03 30 AM](https://user-images.githubusercontent.com/45409515/131361860-5109eeb3-a143-42d5-a057-d6a3ca9b3e69.png)

And if you look at the cart, it's not there.

**Expected Result**
We need a better more informative message for this kind of products that can't be purchased.
In the past, we would get a "Product cannot be purchased" message back.

**Comment by Xymmer** [comment]
As the description of this issue relates directly to multi-d, not yet supported, I'm inclined to say let's look into fixing this for 4.2 in a general way (if there is one). At same time customer is not entering a valid sku, as a multi-d item would be e.g. xyz_1 if parent SKU is xyz. At the very least let's display a proper message, but to be investigated.

**Comment by BenjaminEmiliani** [comment]
I'm not sure if this is worth noting, but, when you are in the Shopping Cart view and try to add the SKU mentioned above, 50500000, to the Quick Order feature under Order Summary, the response is "We could not find any products".
<img width="1511" alt="Screen Shot 2021-09-02 at 10 14 02 AM" src="https://user-images.githubusercontent.com/49131189/131860218-c6aa12a5-daf2-41aa-9b4e-330386872688.png">

**Comment by dydome** [comment]
Hi @KateChuen and @Xymmer I was investigating this issue and have some conclusions:

- in 4.2 version of quick order it looks different now, we are getting a warning message which is also wrong. But API error is also not so helpful. I am not able to recognize that this is because of the non-purchasable type of product as the error looks like:
`message: "The application has encountered an error"
type: "DomainError"`

- another thing is that I was trying to get information from API if the product is non-purchasable, unfortunately changing endpoint with field 'purchasable' or even changing product fields to 'FULL' did not return me purchasable field in response object :(

- another idea is to not allow adding multidimensional products to the list and show some error for this kind of product. But the question is that for now, it is not possible to search for variants (example xxx_1) we are always getting base product if multidimensional  is always non-purchasable I can use this flag to somehow block it

**Comment by dydome** [comment]
Maybe we can also ask @WeizhengSap about it?

**Comment by WeizhengSap** [comment]
1. This product is not `purchasable`, so the `Add To Cart` button should be disabled
2. The error message is very confusing
![Screen Shot 2021-10-26 at 11 14 48 AM](https://user-images.githubusercontent.com/44440575/138897600-c4141807-d480-49c5-81bb-ee34082a88d5.png)

The error message we got from backend is "Error occurred while adding to Basket"

**Comment by dydome** [comment]
Ok thank you @WeizhengSap for your message but still, we are not getting `purchasable` flag in search to somehow validate it before adding to the list and adding to cart error is not enough specific for this so it is risky to handle this as purchasable error :(

**Comment by Xymmer** [comment]
for Bill to follow up

**Comment by dydome** [comment]
@Xymmer there is PR to with workaround fix this issue, I think today it will be merged to develop https://github.com/SAP/spartacus/pull/14129

But @Xymmer is it possible to create a ticket in JIRA for BE to fix the search response to accept and return the purchasable field?
