### ISSUE TITLE
Quick order css: Quantity box is different size for different items

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13579]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.84.65.98

**Steps**
Go to electronics storefront
Click on Quick Order
Add 10 different items

**Actual Result**
The qty box for the items is of different sizes
![Screen Shot 2021-08-31 at 10 37 25 AM](https://user-images.githubusercontent.com/45409515/131523049-b50f3fe4-6e67-40cc-b25c-af9bd006d646.png)

**Expected Result**
The qty box should be the same for all of them

**Comment by morganm58** [comment]
This is not a styling issue. The quantity inputs that a wider are missing `min=""` and `max=""` values in the html. When the same items are in the cart the quantity boxes look fine because the inputs have the min and max values.
<img width="908" alt="Screen Shot 2021-09-02 at 12 17 50 PM" src="https://user-images.githubusercontent.com/2947470/131881033-8740b010-bb6c-42cb-bc13-db368c6e54bc.png">
<img width="1046" alt="Screen Shot 2021-09-02 at 12 20 21 PM" src="https://user-images.githubusercontent.com/2947470/131881036-8ee89960-7102-4c95-b76d-31483f00c8d1.png">

**Comment by morganm58** [comment]
@dydome could you look into this one?

**Comment by dydome** [comment]
I agree that this is because of missing max value, sometimes API does not return stock level information that is why this field is empty, I saw that in cart item component there is another approach -> `[max]="item.product.stock?.stockLevel || 1000"` but this is not fixing the problem as if the other entry has max value with 2 or 3 lengths, for example, "11 or 111' the cx-counter width will be different. So the only way to fix the different widths of the component is to set the static width of the element. Proposed solution here -> https://github.com/SAP/spartacus/pull/13621 @morganm58 please take a look.

**Comment by BenjaminEmiliani** [comment]
@dydome I see that in PR #13621 you added a fixed width to the cx-item-counter element, but I think this causes another issue. The plus button becomes larger on some browsers (picture is from Chrome):
<img width="395" alt="Screen Shot 2021-09-08 at 12 46 23 PM" src="https://user-images.githubusercontent.com/49131189/132550720-a58ae5e4-870e-4bd3-aba6-932c3c60e23a.png">

I think is is because the input part of the element has:
min-width: 48px;
max-width: 78px;

And the button portion only has min-width property.

Something that made it seem good to me on every browser was:
- Give cx-item-counter a fixed width like you did
- Make the input section have a fixed width of 50% (no min-width, no max)
- Make the button section have a fixed width of 25% (since the counter has 2 buttons ->  [ - ][     1    ][ + ] )
