### ISSUE TITLE
Quick order: Adding an out of stock item

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13580]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.84.65.98

**Steps**
Go to apparel-uk storefront
Click on Quick Order
Add an item that's out of stock, eg: Item 300404092

**Actual Result**
It looks like you can edit the qty to whatever number you want.
![Screen Shot 2021-08-31 at 10 54 09 AM](https://user-images.githubusercontent.com/45409515/131525865-50c2edbd-8f9a-4594-9546-d7d72028371a.png)

If you click on Add to cart after that, it looks like it was added successfully. 
![quickorder_outofstock](https://user-images.githubusercontent.com/45409515/131526286-7ce18e9e-6147-4011-8d28-b79a601adb88.png)

**Expected Result**
The qty box should be disabled if the product is out of stock, and the qty should be 0. 
Should get the correct message that the item was not added to cart because it's out of stock.

**Also in powertools**
Have an item out of stock.
Go to quick order
Search for that product
The product is added to the list, with qty 1. 

![Screen Shot 2021-08-30 at 3 26 54 PM](https://user-images.githubusercontent.com/45409515/131394490-c4b09e35-d365-467f-aa63-4d96e956efaf.png)

Should we allow adding out of stock products in the list? Perhaps the qty should be 0 if it's listed in quick order.
Although we can't add it to cart, we get the right message that the item is out of stock. But as a user, I don't see that, until I go ahead and add it to cart.

But in powertools, it displays the out of stock message as expected, when we try to add it to cart. 
![Screen Shot 2021-08-30 at 1 28 37 PM](https://user-images.githubusercontent.com/45409515/131686880-be263fe4-af2d-4032-9504-a00ebc44d3d3.png)

**Comment by psmul** [comment]
Currently opened pull request (#13594) fixes notification if we're trying to add out of stock product. (below you see result once PR gets merged)
![image](https://user-images.githubusercontent.com/10993491/131853607-d3a02780-8f79-41de-a80b-24f554195fa2.png)



Implementation/changes for products quantity counter haven't been made, because this requires further discussion in term of UI mainly.  In case of quantity = 0, our counter component won't block elements but will replace it with the simple text "0". I'm not sure if that's what we want to achieve or preferably display user information highlighting the product being out of stock.
