### ISSUE TITLE
Quick Order: Should show the reached limit message only after the 10th item

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13597]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.84.65.98

**Steps**
Go to Powertools storefront
Go to Quick Order
Add 9 items in the list
Type the sku for the 10th item and press Enter

**Actual Result**
When I search my 10th item in the quick order, it's added to the list. But then, what I see as a user is this message: 
![Screen Shot 2021-08-30 at 10 55 16 AM](https://user-images.githubusercontent.com/45409515/131363352-324446af-20ad-41dd-a756-a6d70208625c.png)

**Expected Result**
Which at first glance, makes me think that the item was not added, because I had reached the maximum. 
So, I don't really know how we can handle it better. 
What I would have expected instead is, just disable the search box. But then, I would not know why it is disabled. 
Unless we don't disable it, allow user to add a SKU, but when he does, then we display this error message?

**Comment by dydome** [comment]
@KateChuen  I wrote to UX team to get some information how to deal with it.

**Comment by Manurod2018** [comment]
In order to avoid the user's confusion, I suggest that the error message would be displayed only after the user typed the 11th SKU number. Also, we should add a message that will help the user know what to do next, so he doesn't feel stuck, ex: The list is full, add these 10 products to Cart in order to continue.

Additionally, we could add a way to warn them, as they get close to the limit, by displaying a countdown? (1 product left...) Unless we don't want to put too much emphasis on the fact that there is a limitation.

**Comment by dydome** [comment]
@Manurod2018 I have created PR to change the form mechanism but may you please prepare for me some proposition how to show some countdown and where?

**Comment by Manurod2018** [comment]
![D - B2B - ADD SKU - Error](https://user-images.githubusercontent.com/37299626/138482693-848b594d-a7cf-4eac-affe-bd6b5500edca.png)

Sorry, after reflection the countdown would probably attract too much attention and it would lead to more confusion. As a matter of fact, they already have the text on the bottom of the title which states that they can only add up to 10 valid SKUs at a time.

Here's an example of the error being triggered after the user starts typing the 11th SKU number, I believe it is a much simpler solution.
