### ISSUE TITLE
ParagraphComponent does not make anchor link with #id work as expected

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#14108]
How to reproduce:
1. go to `FAQ` page by clicking `Help` in the header
2. click any links (such as "Returns and refunds") will redirect to homepage

The content of the `ParagraphComponent` contains the anchor link, e.g.:
`<a href="#b00">Delivery information</a>` and `<h2><a id="b00"></a>Delivery information</h2>`

But, in html, `[innerHTML]="data.content"` remove the id.

**Comment by Xymmer** [comment]
Reported by customer

**Comment by Pucek9** [comment]
Maybe it depends on server, but on CI' one I have response
```html
<li><a href="#b00">Delivery information</a></li>
<h2><a name="b00"></a>Delivery information</h2>
```
or
```html
<a class="faq-menulink" href="#b01">Delivery Options</a>
<h3><a name="b01"></a>Delivery Options</h3>
```
here is `name` instead of `id`, and yep -> `name` is not rendered
![image](https://user-images.githubusercontent.com/8040837/138970858-825f625d-7aa2-4342-a588-16d9a6469a26.png)
my IDE is telling me also that this is deprecated (not sure we support it)

----------------
Im afraid about more issues:
`<a href="#b00">Delivery information</a>` would not work even proper id usage, it should be ->
`<a href="/electronics-spa/en/USD/faq#b00">Delivery information</a>`

**Comment by WeizhengSap** [comment]
@Pucek9 : We have to add anchor in smartedit, then you will see the id. (I will add anchors for "Delivery information" and "Returns and refunds")

**Comment by Xymmer** [comment]
Is this issue same as #915 ?

**Comment by Pucek9** [comment]
> Is this issue same as #915 ?

seems yes

**Comment by Pucek9** [comment]
The issue with a link with missing path (including base site, language, currency, rest of path) has been fixed by #14137 

Removed `id`/`name` tags is a security problem: As Spartacus, we can not sanitize this HTML received from the backend without using 3rd party libs (we don't want to do that). 

**[Not recommended]**
The solution provided by angular (you can meet as a common response in StackOverflow) allows for sanitize the whole HTML file and it's not a secure scenario in our opinion:
```ts
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Pipe({ name: 'cxSafeHtml' })
export class SafeHtmlPipe implements PipeTransform {
  constructor(protected sanitizer: DomSanitizer) {}

  public transform(html: string): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }
}
```
At least until angular doesn't [support custom attributes](https://github.com/angular/angular/issues/36650), we wouldn't like to add `cxSafeHtml` pipe to Spartacus.

**[Recommended]**
The other way is to create `yourSafeHtml` pipe where you use other libs like [sanitize-html](https://www.npmjs.com/package/sanitize-html) or [dompurify](https://www.npmjs.com/package/dompurify) and configure `id`, `name` attributes to be allowed.

Then, you should extend our `ParagraphComponent` with template like:
```html
<p
  *ngIf="component.data$ | async as data"
  [innerHTML]="data.content | cxSupplementHashAnchors | yourSafeHtml"
></p>
```

**Comment by Pucek9** [comment]
Recommended solution:

1 Add lib: `yarn add dompurify`
2 Create pipe and declare it in some module:
```ts
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import DOMPurify from 'dompurify';

@Pipe({ name: 'yourSafeHtml' })
export class SafeHtmlPipe implements PipeTransform {
  constructor(protected sanitizer: DomSanitizer) {}

  transform(html: string, attributes: string[]): SafeHtml {
    const cleanHTML = DOMPurify.sanitize(html, {
      ADD_TAGS: attributes,
    });
    return this.sanitizer.bypassSecurityTrustHtml(cleanHTML);
  }
}
```
3 Create `YourParagraphComponent` based on our ParagraphComponent
```ts
@Component({
  selector: 'your-paragraph',
  templateUrl: './your-paragraph.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class YourParagraphComponent extends ParagraphComponent {
  constructor(public component: CmsComponentData<CmsParagraphComponent>) {
    super(component);
  }
}
```
 with template like:
```html
<p
  *ngIf="component.data$ | async as data"
  [innerHTML]="data.content | cxSupplementHashAnchors | yourSafeHtml: ['id', 'name']"
></p>
```
4 Set cms configuration
```ts
 cmsComponents: {
    CMSParagraphComponent: {
      component: YourParagraphComponent,
    },
    //...
  }.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by giancorderoortiz** [comment]
Fix seen.
