### ISSUE TITLE
[backend fix needed] Image Zoom: No thumbnails on 2105 [works in 2011]

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14135]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4 (Pointing to 2105 backend)

**Steps to Reproduce**
Go to electronics storefront
Go to pdp of this product: 1934793
Click on "Expand Image"

**Actual Result:**
There's no thumbnails for this product in 2105. Same deployment, pointing to 2011 has the thumbnails. 2105 is using same sample data as 2011.

![Screen Shot 2021-10-27 at 3 04 05 PM](https://user-images.githubusercontent.com/45409515/139130404-d0440f43-e20b-47b8-9c62-a0c48a9eb473.png)

Talked with Michal, he said it's because the products don’t contain product.images.GALLERY in 2105. They tried importing through impex, but that did not work either.

**Comment by Xymmer** [comment]
- can there be a problem with image zoom? A: we don't think so, it works in 2011, not 2105
- is there a bug in 2105? occ call not returning image gallery information
- was there a change in how the occ call works? e.g. when checkout stopped working, it was because of a removal of deprecated code during refactoring of occ

Investigate to determine the above, fix or create CXEC jira ticket depending on results.
Talk to OCC team(s) to be sure. (Talk to Bill to find out who)

**Comment by Xymmer** [comment]
fix will be in CXEC-5086

**Comment by Xymmer** [comment]
closed and moved to https://jira.tools.sap/browse/CXSPA-306
not sure we have to do anything but we'll test
