### ISSUE TITLE
Scrolling Restoration Improvement 

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14197]
**Description**
When navigating back and forth between Product Results List and a Product display page, the scrolling restoration from the Product Results List is applied to the PDP even though no scrolling was done in PDP.

**Version of Spartacus**
- RC 4.2 using CX 2105 - CSR B2C 

**To Reproduce**
1. Click on a catalog such as 'CAMCORDERS' 
2. Scroll down
3. Click on any particular product
4. Without applying any scroll, click on the browser's previous page button
5. When you land back on the 'CAMCORDERS' results list, click on the browser's next page button
6. Notice that the scrolling restoration from the list of results is applied to the PDP 

**Expected Behaviour**
No scroll restoration applied when a user does not scroll on a page 

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser [chrome and safari]

**Comment by justinlee01** [comment]
Investigation:

The Spartacus code uses Angular's Router events to memorize the user's last scroll position for routes and caches them. When the user clicks 'Back', the scroll position is then memorized for that route, as expected.

However, on PDP, before the code can record the user's current scroll, the page is scrolled down by some amount (not confirmed whether it's equal to the previous page's anchor), therefore Spartacus records the wrong amount.

This mysterious scroll event does not originate from Spartacus itself or Angular. It occurs before any NavigationStart is emitted. It's reproducible on Chrome, Safari, FF.

I'm setting down this ticket because 1) the ideal solution is to prevent this unwarranted scroll and 2) I can't think of a way forward in the investigation.

**Comment by kimhw0630** [comment]
adding scrollPositionRestoration: ‘enabled’ in app routing module seems to fix the scrolling issue..

![image](https://user-images.githubusercontent.com/11823988/159038596-9b3e73ae-b3c4-4a53-a063-34bb34958306.png)

**Comment by Xymmer** [comment]
Ticket moved to https://jira.tools.sap/browse/CXSPA-303
