### ISSUE TITLE
Styling on cart entry total of 10k+ is misaligned in desktop view

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#14229]
**Describe the bug**
The total for a cart entry that exceed 10k+ shows a misalignment and wraps the last digit

**To Reproduce**
1. Add product to cart that makes the entry total bigger than 10k
2. See wrapped text

**Screenshots*
![Screen Shot 2021-11-03 at 4 23 12 PM](https://user-images.githubusercontent.com/29099466/140187575-9c8d1f6a-129c-4abf-a59e-03e08dc1fed0.png)
![Screen Shot 2021-11-03 at 4 27 32 PM](https://user-images.githubusercontent.com/29099466/140187581-19be67fc-b3c6-4d01-aea6-214c94ffbeae.png)
*

**Comment by Xymmer** [comment]
checking if related to 4.2 style version

**Comment by developpeurweb** [comment]
@morganm58 @Xymmer 
- This issue was addressed in ticket GH-14096. The wrapping is part of a temporary fix. However, a more permanent solution is needed. but...
- Since the cart tables aren't real tables, but in fact Bootstrap columns, it will have to be yet another temporary fix, that could aim to override BS values. E.g. `.cx-total {padding: 0;}`. Still, since most "non-tables" are to be refactored and Bootstrap deprecated I suggest pushing this ticket to 5.0 and asking for feedback from designers when that happens, to set a limit for wrapping. 
- **Keep in mind some currencies have way too many zeros, and some wrapping will have to take place after a certain limit.**
