### ISSUE TITLE
Using $font-size-base Can't Override the body Font Size from 1rem to 0.875rem

### ISSUE THREAD

**Issue by huboo** [SAP/spartacus#14305]
**Describe the bug**
On styles.scss using `$font-size-base: 0.875rem;` can not override it.

**Tell us the version of Spartacus**
- Library version: 4.1.1

**To Reproduce**
1. Go to 'src/styles.scss'
2. Add `$font-size-base: 0.875rem;` above `@import '~@spartacus/styles/index';`
3. Save and check body font-size
4. Expect `font-size: 0.875rem;` but got `font-size: 1rem;`

**Possible fix**
https://github.com/SAP/spartacus/blob/b88f32f407c8fd4c1b82570b32f57fd7f849b8c5/projects/storefrontstyles/scss/theme/sparta/_variables.scss#L55

add `!default` after.

And not `@import "@spartacus/cart";` on `src/styles/spartacus/cart.scss`

**Comment by Xymmer** [comment]
to investigate and repro

**Comment by cmanciero** [comment]
If i am understanding the problem correctly. It seems that the styling is not being applied because the _reboot.scss file is being loaded 4 times when the page load. This call to the _reboot.scss file is coming from *bootstrap*. You can see from the attached screenshot that after adding the **!default** keyword to the _variable.sccs file the new font-size is applied, only to be overwritten when the bootstrap styles are added

![Screen Shot 2022-03-08 at 12 13 33 PM](https://user-images.githubusercontent.com/664825/157290115-81065577-b139-46ab-bfc6-0b4d6c845c5a.png)

**Comment by morganm58** [comment]
One solution might be to move to the latest sass and bootstrap. Sass uses @forward and @use now instead of import. One of the reasons they changed it is because of the duplication of imported styles. Bootstrap would also need to be updated to the latest version as well. The version of bootstrap that we use right now does not support the @use and @forward in sass.

**Comment by morganm58** [comment]
This is fixed in GH-15534

**Comment by KateChuen** [comment]
Tested locally using yarn on develop branch. 

Ok now, adding `$font-size-base: 0.875rem; ` in `src/styles.scss`
loads `font-size: 0.875rem;`

<img width="672" alt="Screen Shot 2022-05-30 at 3 31 53 PM" src="https://user-images.githubusercontent.com/45409515/171051634-825a200d-e058-45ca-ad59-1855f4f7e607.png">


Checked for other values too, and it loads properly.

<img width="818" alt="Screen Shot 2022-05-30 at 3 33 34 PM" src="https://user-images.githubusercontent.com/45409515/171051630-0fae472b-e334-4a8f-96c1-13c4d538bf6b.png">


And is no value is specified, the font size is 1 by default.
