### ISSUE TITLE
Fix i18n back-end configuration for http client

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#14458]
In 4.0 we've switched from `i18next-xhr-backend` to `i18next-http-backend`, but it seems the config passed to the new library doesn't match the old one.

**Comment by Platonn** [comment]
IMHO the impact of this bug was nearly nothing, so no need to backport

Reasoning:
The reason we introduced as i18next middleware the Angular HttpClient, is that in the past it used by default xhr, which was not available in Node.js ( it simply didn’t work in SSR!)

Thanks to Angular HttpClient being smart -> in csr it uses xhr api, but in ssr, it uses fetch api

but since we switched to new dependency i18next-HTTP-backend, it’s smart enough to recognize csr/ssr itself and use xhr/fetch accordingly

and even if our middleware (using Angular HttpClient) was ignored since 4.0 [DUE TO THIS BUG TICKET], no problem, becasue switching to i18next-http-backned actually solved the same problem and our middleware become unnecessary

However, plugging Angular HttpClient is nice anyway, becasue you can apply a standard http interceptor to amend the calls for JSON translations - which might be useful for customers. That’s  why I didn’t propose to drop it.
