### ISSUE TITLE
Race condition in add to cart

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#14696]
There is a race condition [here](https://github.com/SAP/spartacus/blob/epic/cart-lib/feature-libs/cart/main/core/facade/active-cart.service.ts#L298-L300) 

If `activeCartId$` emits before `cartSelector$`, the values are dismissed by the `withLatestFrom` operator.  If `activeCartId$` doesn't emit any more values, then the stream is stuck and does not emit anything. From the user's perspective, he clicks "add to cart" and nothing happens.

Part of the fix is implemented [in this PR](https://github.com/SAP/spartacus/pull/14643).  Removing the filter from `cartSelector$` helps.

We need to verify if [the filter for guest merge](https://github.com/SAP/spartacus/blob/epic/cart-lib/feature-libs/cart/main/core/facade/active-cart.service.ts#L293) could also create an issue. 

Also we need to be careful not to introduce [an issue that was solved there recently](https://github.com/SAP/spartacus/issues/13645).

**Comment by WeizhengSap** [comment]
`cartSelector$` is used in `withLatestFrom`, but also 2 `switchMapTo`. We cannot remove the filter, because only when `loading` is done, cart can be `created`, and only `creating` is done, the required cart can be read. 

When `requireLoadedCart` is called, `cartSelector$` state is loading. This only happens when `addEntry` is called but `initActiveCart` (which in constructor) is still loading. In this ticket https://github.com/SAP/spartacus/issues/14416, it may be possible that cart-lib is loaded only when "add to cart" is clicked. So, that's why this race condition happens. 

What we need to do is to make sure that the state `isStable` before "add to cart".
