### ISSUE TITLE
Enhance Models and Normalizer

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#15195]
Add intervalInDomain flag:
Both: variant-configurator-occ.models.ts and configurator.models.ts

Add placeHolder field:
configurator.models.ts

Normalizer:
1. Set intervalInDomain flag
2. Fill placeholder field
3. Unit-test for placeholder

**Comment by JayEmKay-8** [comment]
From a usability point of view it is a bit confusing that in the case of "Single interval with single number" a number disappears from the explanatory text when I enter it:
_Enter a value between 5 and 10 or enter 15 or enter a value between 20 and 30_
If I enter "15", the following text remains:
_Enter a value between 5 and 10 or enter a value between 20 and 30_
This is confusing to users.
However, since having single numbers between intervals is an edge case in my opinion, and since customers can adapt these texts, I'm willing to accept this as it is now.
