### ISSUE TITLE
Able to checkout as anonymous in B2B if get 401 at login

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15330]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local (installed using script)
Backend: 40.76.109.9

**Steps to Reproduce**
Login on powertools storefront
Have items in cart.
Click on "Proceed to checkout"
Login -> But try to get a 401 and user not able to login.

**Actual Result**
I don't know how I'm getting the 401 (I'm still investigating). 
But when I get the 401, instead of remaining on the login page with an error message, they display the checkout step, like an anonymous user. 
And I'm able to checkout. 
<img width="1433" alt="Screen Shot 2022-03-08 at 2 35 51 PM" src="https://user-images.githubusercontent.com/45409515/157319501-a3d4dcc2-8cbf-45a0-a118-cc641744a0c6.png">

**Expected Result**
I thought we should not able checkout as anonymous user on B2B.

**Comment by Xymmer** [comment]
to investigate if this is spartacus falling back to b2c-style anon checkout, or if it's backend issue

**Comment by bgambocjaviniar** [comment]
To verify, but I'm assuming the response returned from that 401 is saying we're in the wrong channel. Most likely need to update the local installation script if it doesn't use the correct channel

If that's the case, it is normal because somehow we're logged in when we get wrong channel error. --> if it really is the case, then something to look into for our **Auth process** as somehow we're logged in when we get an error **(big issue if that's the case)**

**Comment by bgambocjaviniar** [comment]
should be good as discussed, but to verify and double check the installation script again

**Comment by KateChuen** [comment]
Not getting 401 now, when set ADD_B2B_LIBS=true. 
But do we want to tackle the issue, where when we get 401 (wrong channel), it looked like we're placing order as anonymous? But we really are logged int? It's ambiguous... 
@Xymmer @bgambocjaviniar

**Comment by bgambocjaviniar** [comment]
think it's an issue, but not a security risk @Xymmer @giancorderoortiz (to confirm)

because I see it as if the customer gets this error, then they misconfigured their storefront.

**Comment by Xymmer** [comment]
moved to https://jira.tools.sap/browse/CXSPA-278
