### ISSUE TITLE
ASM lib doesn't allow for override styles

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#15434]
**Describe the bug**
Most libraries have separated `styles` part. Styling in ASM is placed together with components, and styles are not exported.

**Tell us the version of Spartacus**
- Library version: 4

**Expected behavior**
We would like to have
`feature-libs/asm/_index.scss`
`feature-libs/asm/styles` with all files
and everything which is necessary to allow for overriding

**Additional context**
Please remember about usage placeholder selectors (%)

**Comment by Platonn** [comment]
It causes problems with customizability. There are 2 workarounds for customiaztions, depending on the customer use case:

a) if you only want to tweak styles, but keep original HTML and TS -> then you can try simply writing custom global CSS rules targeting the original component’s selectors e.g. `cx-asm-main-ui { … }`. It should be possible, because ASM components have local styles pre-compiled for the component, but not strictly encapsulated:
https://github.com/SAP/spartacus/blob/a1421cf95481c6f2b59926a91f4e9380ff10f70b/feature-libs/asm/components/asm-main-ui/asm-main-ui.component.ts#L24-L25

b) if you want to tweak TS and/or HTML -> then you’re likely creating custom component TS class _extending_ from the original TS class. In that case you loose the original SCSS (becasue styles from the decorator `@Component` of the original class are not inherited by the child class). Then it's a bummer, you need to copy-paste the original SCSS from the source code. That’s the workaround.

**Comment by Xymmer** [comment]
pls also see request https://github.com/SAP/spartacus/issues/15449 for improvement, is it same or can be done at same time as this fix?

**Comment by Pucek9** [comment]
> pls also see request #15449 for improvement, is it same or can be done at same time as this fix?

The purpose of this ticket is to separate cx-outlets for each component inside so that it can be easily replaced. These are independent things

**Comment by Pucek9** [comment]
Moved to https://jira.tools.sap/browse/CXSPA-238

**Comment by Xymmer** [comment]
backport to 4.x and 3.x (if possible)
