### ISSUE TITLE
sass error when using the installation script

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15451]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local 
Backend: 40.76.109.9

**Steps to Reproduce**
Clone spartacus repo
Checkout the develop branch
Go to scripts/install
run `./run.sh install`
Once the previous step is done, run `./run.sh start`

**Actual Result**
This error is displayed when starting the storefront
![Screen Shot 2022-03-24 at 12 45 05 PM](https://user-images.githubusercontent.com/45409515/159968737-b7730c48-0489-407a-a13d-b77d1cf0b99c.png)

**Expected Result**
Should be able to start the storefront using the installation script

**Comment by Xymmer** [comment]
new info: brian says it will be fixed with https://github.com/SAP/spartacus/issues/15451

**Comment by developpeurweb** [comment]
@Xymmer @bgambocjaviniar 
Not sure if those bugs are related to "SASS known bugs", just a reminder that we can't upgrade SASS until we drop Bootstrap4 since it doesn't support `@use` (a new SASS feature).

- Ticket to [fix SASS](https://github.com/SAP/spartacus/issues/12336)
- Ticket to [Remove Bootstrap](https://github.com/SAP/spartacus/issues/13012)

**Comment by KateChuen** [comment]
It's fixed now. Verified on my local and on a vm.
