### ISSUE TITLE
Translation parameter string value show in the UI after Angular upgrade

### ISSUE THREAD

**Issue by kimhw0630** [SAP/spartacus#15561]
After we upgrade to the new version of Angular 13, if we don't pass the translation parameter it shows in the UI

1. Go to My Account -> My Company -> Units
When editing a unit,  button text for Save shows as. Save {{NAME})
also in the delivery address section Create {{NAME}}

![image](https://user-images.githubusercontent.com/11823988/161987201-19c8d9b1-73dc-4291-8240-b5c2f643e947.png)

![image](https://user-images.githubusercontent.com/11823988/161987238-7dd6e6ea-ce6d-4753-81fa-6fe8ff5389dd.png)

**Comment by developpeurweb** [comment]
I was pointed towards this ticket because something similar is happening on PLP, and affecting Screen Reader narration for facets filters, therefore it's a regression for PLP as well.
<img width="702" alt="Screen Shot 2022-04-06 at 3 07 42 PM" src="https://user-images.githubusercontent.com/15113219/162053170-fd8253ac-fe59-4f3e-a03d-d12851cdacd1.png">

**Comment by KateChuen** [comment]
Tested on develop branch using yarn.

Looks ok now.
![Screen Shot 2022-04-20 at 11 44 05 AM](https://user-images.githubusercontent.com/45409515/164273949-c8a578ea-e1b2-432d-9a36-3980230f4f87.png)

![Screen Shot 2022-04-20 at 11 44 27 AM](https://user-images.githubusercontent.com/45409515/164273967-d660cef7-1252-4746-95ce-4c36c7b0cd30.png)

![plp](https://user-images.githubusercontent.com/45409515/164273975-34bf0b13-c9dd-4db4-a093-520794da4754.png)
