### ISSUE TITLE
Screen position issue when navigating from conflict

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#15565]
Configure color test product. Create conflict by setting colour to 'Indigo' and 'Trigger Value Conflict' to 'Yes'.
Navigate to the conflict by clicking on '[Conflict Detected - View Details]' for 'indigo'.

Navigate back by hitting '[View In Configuration]' for 'Trigger Value Conflict'. The system navigates to general group correctly but does not set the focus correctly.

This task also uses GH-15498 Branch

**Comment by Uli-Tiger** [comment]
can only be tested with local setup, as it requires hybris 2205

**Comment by Uli-Tiger** [comment]
Tested this with color test product locally, but can also reproduced on team server with Home_THEATER_SYSTEM.
The focus is now correctly set on the value, but the view port is not positioned properly. The focused element is not visible.
repro: 
- configure color_test_product
- select Cause restriction conflict - YES
- navigate to conflict group (**via Hamburger menu, not via link!**)
- click view in configuration
The conflicting value has focus, but it is not visible in the view port of the browser.
expected: focused element is visible in the view-port of the browser . See also screenshot
![image](https://user-images.githubusercontent.com/53090888/167385745-62931ce9-61cc-4265-beb3-1fd3c0d7f0fe.png)

**Comment by steinsebastian** [comment]
Cannot be reproduced with Chrome. Only reproducible in Firefox.
Need to find out, whether we can provide special handling for Firefox.

**Comment by steinsebastian** [comment]
Debugged this issue:

In general: before the scroll method is called in order to position the attribute at the top of the screen it is checked whether the target attribute is in the viewport. If this is the case no scrolling is done, if it is not in the viewport it is scrolled to the attribute.

If you navigate from the original group via "Conflict Detected - View Details" link to conflict group and then navigate back via "View in Configuration" the target attribute is not in the viewport therefore scrolling is done.
 
In Firefox if you navigate from the original group via "Hamburger" Menu to conflict group and then navigate back via "View in Configuration" the target attribute is already in the viewport (but only at the bottom). Therefore the check before the scroll-method (isInViewport) returns false and therefore no scrolling is done.
The question is now: why is the attribute in the "Hambuerger"-menu-navigation-case already at the bottom of the viewport?!?

**Comment by steinsebastian** [comment]
It seems that Firefox also scrolls if the focus() method is called in some ocassions.
Therefore executing the focus() method before the scroll method might lead to the fact that the attribute is at the bottom of the viewport and therefore no scrolling to the top of the viewport is executed.

Another issue is that the isInViewport method does not consider the sticky add-to-cart container. That means if an element is hidden behind this container the method will consider it to be "in the viewport" although it is not visible to the user.

**Comment by steinsebastian** [comment]
A simple solution could be to remove method isInViewport and always scroll the attribute to the top of the viewport regardless its position in or outside the viewport
