### ISSUE TITLE
Tags and Release branches for latest releases are missing

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#17736]
**Describe the bug**
For the latest Releases 6.2.0 and 6.1.0, Release branches and Tags where not created any more. Those are crucial for developers using Spartacus in the open source variant by building it themselfs. We build spartacu projects for customers having a CCV2 License, but still need the open source variant for internal dev purposes and quickly trying things out.

**Tell us the version of Spartacus**
- Library version: 6.2.0 / 6.1.0

**To Reproduce**
1. Try to build spartacus from open source
2. Notice that there is neither a Tag nor a release branch for the latest release 6.2.0

**Expected behavior**
A release branch or at least a tag is being created, so it can be used for open source builds

**Screenshots**
![Pasted_Image_06_08_23__17_25](https://github.com/SAP/spartacus/assets/3381820/5421068e-e10e-4e68-8296-3b852367f324)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all
**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**

**Comment by janwidmer** [comment]
Tags have been created now.. release branches still missing..

**Comment by Platonn** [comment]
Hi @janwidmer 
Since 6.1 we've changed the naming convention for the release branches, now they are named `develop-6.1.x`, `develop-6.2.x`, ... (please mind the separator is `-`, but not `/`)

Before 6.1 we used `develop` branch for the ongoing development and we cut-off stable release branches from it: `release/5.1.x`, `release/5.2.x`, ...

Since 6.1 we use a "named develop" branch for the ongoing development, e.g. `develop-6.1.x`. When we want to stabilize this release, we simply cut-off a new branch `develop-6.2.x` which becomes the new `develop` (for ongoing development) and the branch `develop-6.1.x` becomes implicitly the release branch for the version 6.1.

**Comment by janwidmer** [comment]
@Platonn aaaah thanks for the explanation, that makes sense.. We have now created our locally hosted builds based on the tags, which where also created recently..or as last resort, downloading the sources of a release and building it from there ;-)
