### ISSUE TITLE
Star rating doesn't seem to support SVGs [already fixed?]

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#2469]
This ticket addresses specifically the issue of star-rating for product not working with custom SVGs as per screenshot below.

![Screen Shot 2019-05-14 at 11 50 04 AM](https://user-images.githubusercontent.com/15113219/57718835-58bec480-764c-11e9-88c8-4fc273bacb21.png)

**Comment by tobi-or-not-tobi** [comment]
This is indeed not possible out of the box. The CSS rules we provide in our style lib use the CSS variable `--star-fill` in a linear gradient. While CSS rules and CSS variables peers through the SVG DOM, the CSS gradient implementation doesn't work in SVG, since SVG has it's own gradient system. We could make this technically work, but we dot waste the effort here. If customers want to use SVG icons for the star rating component, they could build this or use an alternative approach to render the color on the icon. 

This would require:
- introduce SVGs `linearGradient` in the star icon
- connect the linearGradient color system to the CSS variable `--star-fill` and `--cx-color-primary` and `--cx-color-light`.
