### ISSUE TITLE
Change "Your shopping cart" to "Shopping cart" in backend sample data

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#2910]
because it's backend, we can't fix it in GH-2785

**Comment by bgambocjaviniar** [comment]
@Xymmer  Shouldn't this be done in the b2c-addon for the backend change 'Shopping Cart'? Because it shouldn't only be a fix for spa. Can you create a ticket for c3po please

**Comment by bgambocjaviniar** [comment]
Other than that backend 'issue', shouldn't we follow the wireframes? Another point to this is the cart # because I don't think the user needs to know the cart # before purchasing the item. I'm guessing this unique id for cart is going to be used for the order confirmation too. 
---> Might be a bug or a feature, but the cart # at the beginning and after purchasing it is different by 1. For example, at the cart page it would be 0001, and in the confirmation after checking out, it would be 0002.
