### ISSUE TITLE
Improvements to login error flow

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3003]
Currently if you repeatedly incorrectly entire login information, same message appears at top. It's confusing because it seems like nothing's happened.
![image](https://user-images.githubusercontent.com/4998145/59200080-7278fc00-8b65-11e9-826e-037eb4fd0a49.png)

The request here is, take a look at http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login:

- Provide specific flow improvement for activation of Sign In button according to best practices that Anthony worked out with Patrick a while back.
- Should we display a message below email field stating they didn't enter a correctly-formatted email?
- We're not supposed to say the password specifically is wrong, suggest a message better than "Bad credentials. Please login again." 
- but also, how do we highlight to the user that the same message has re-appeared?

**Comment by vekterdude** [comment]
Here is a link to the relevant wireframe(s): https://98qkkl.axshare.com/#g=1&p=d_sign_in_default 
(All breakpoints and states are described below)
pass: sparticus

Easy Stuff first:
1. Please call the page 'Sign In' (as per wireframe) and not "Login" since this is consumer-facing software and not backend dev tooling.
2. Please change the error message to the message written in the wireframe: "Email and password do not match"
3. Please change the label on the button to "SIGN IN AND CONTINUE" as per the wireframe
4. Please add the manual "x" close button as per the wireframe


Now, the harder stuff:
Greyed out (disabled) action buttons are not part of consumer-facing browser-based applications. Never grey out buttons in SPArtacus. If you see a greyed out button, contact me immediately!
1. The "SIGN IN  AND CONTINUE BUTTON" should be always enabled. Remove the default disabling of this button for users arriving to the page. This button should NEVER be disabled!

FOR THIS RELEASE ONLY behaviour starts here:
2. If a user, clicks on the [SIGN IN AND CONTINUE] button with no form information filled in the system will display the red error message: "Email and password do not match"
3. When the error message is generated, the form information entered by the user should not be erased, but the text should turn into a red error color specified in the visuals guidelines.
4. When the user places their cursor into either of the red error form fields (both email and password are always in error together for security reasons), BOTH form fields will be reset to empty and new typed entries by the user should appear in the standard text color as described in the visuals guidelines, not in the red error color)
5. This message will persist until A) the user closes the message  by using the "X" close button on the right of the notification. B) The user navigates away from the page. C) 7 seconds has elapsed since the user last clicked on the [SIGN IN AND CONTINUE] button.
6. If the user is able to change their information and click the action button before 7 seconds has elapsed and the new form info is either empty or the email and password do not match, the user will not be able to see any change in the page, but the 7 second timeout on the error message will be reset to 0 and begin counting to 7 again.
7. If user lets the 7 seconds elapse (causing the error message to disappear) changes nothing and clicks the action button again, the "password mismatch" error will reappear and the 7 second counter will begin again.

**Comment by vekterdude** [comment]
Also relevant pages from the wireframe guidelines:
Guidelines concerning notifications: https://98qkkl.axshare.com/#g=1&p=notification_banners_introduction 

Guidelines concerning How Notifications are Cleared:
https://98qkkl.axshare.com/#g=1&p=how_notifications_are_cleared

**Comment by vekterdude** [comment]
![d_sign_in_default](https://user-images.githubusercontent.com/44620139/59222436-7b82c100-8b97-11e9-9953-8496b798c779.png)

**Comment by kacperknapik** [comment]
I'm taking this, since it's block accessibility tests

**Comment by kacperknapik** [comment]
I have to leave this now, since each of the above changes are breaking changes (for most of them we cannot use our anti-breaking-change mechanisms)

**Comment by gandhiharshgit** [comment]
How can i get access to the spartacus wireframes ?
