### ISSUE TITLE
Write review- rating set before I set it, tapping doesn’t work or is weird (iPad Air Safari horizontal)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3128]
Seen in iPad Air Safari horizontal

**Comment by Xymmer** [comment]
![IMG_0019](https://user-images.githubusercontent.com/4998145/59394306-22f52480-8d4d-11e9-87fb-2f4795ad5b43.PNG)

**Comment by developpeurweb** [comment]
This is **no longer an issue**, the rating component has been refactored since. I don't have a real iPad, but it seems to work fine on all simulators, as pre screenshot. Tested on public instance https://spartacus.c39j2-walkersde1-d3-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/product/553637/NV10
@Xymmer can you please retest with your iPad.

<img width="935" alt="Screen Shot 2020-05-14 at 2 53 06 PM" src="https://user-images.githubusercontent.com/15113219/81974181-32cb5780-95f3-11ea-9108-48c99e41d575.png">

<img width="1098" alt="Screen Shot 2020-05-14 at 2 47 55 PM" src="https://user-images.githubusercontent.com/15113219/81974193-37900b80-95f3-11ea-8728-14e3a3233113.png">

<img width="1166" alt="Screen Shot 2020-05-14 at 2 50 05 PM" src="https://user-images.githubusercontent.com/15113219/81974206-3e1e8300-95f3-11ea-8342-d61c2563635d.png">

**Comment by giancorderoortiz** [comment]
Issue no longer seen. 
Tested on Ipad safari and chrome. 


![review1](https://user-images.githubusercontent.com/46171897/82896028-3def8300-9f23-11ea-8f94-d30d123b35f7.png)
![review2](https://user-images.githubusercontent.com/46171897/82896035-3fb94680-9f23-11ea-8168-869fa4ea76bb.png)
![review3](https://user-images.githubusercontent.com/46171897/82896038-40ea7380-9f23-11ea-8e55-7d757c6fc045.png)
