### ISSUE TITLE
During checkout shipping, autopopulate first and last name with login defaults

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3133]
Seems weird that we don't automatically add the user's first and last name into the shipping first and last name fields, especially if they have just registered.

**Comment by benmarcotte** [comment]
Before I start on this, it might be better to leave as-is, since browsers are able to do this themselves once you click on a field. I personally haven't typed my name, address or card number in years because Chrome just does it for me. Not sure if having it be auto-populated might be useless if my browser is just gonna write over it immediately.
