### ISSUE TITLE
Safari auto fill mixes up first and last name - meta data needed? (iPad Air Safari horizontal)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3134]
Seen in iPad Air Safari vertical but likely applies to all Safari's
Reported a while ago so see if it's still happening.

**Comment by Fonsu** [comment]
Cannot reproduce on Catalina using Safari 13.1 (15609.1.20.111.8), tested on desktop and Responsive Design Mode. Tried legacy as well as more up to date environments.

As per a bit of research I have done, [Safari relies on the `autocomplete` attribute](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element). Since we do not use it, it [seems to fall back to the placeholder](https://stackoverflow.com/questions/45461278/safari-autofill-populates-any-field-with-a-placeholder-attribute-containing-the) to try and autofill a given input.

I think it will likely work on iPad Air. It should be tested to be sure but I do not own or have access to one at the moment.

**Comment by Xymmer** [comment]
checking, if i can't repro, we'll close it
however i've asked why we don't use the autocomplete attribute, if that will make it work better

**Comment by Xymmer** [comment]
closing as there's another ticket for adding the proper attributes that will solve this problem
