### ISSUE TITLE
Spike captcha

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3388]
We have a catpcha addon - see the [Accelerator help document](https://help.sap.com/viewer/4c33bf189ab9409e84e589295c36d96e/latest/en-US/8ac8663086691014ab34b77436f85412.html).

Let's implement same in Spartacus for registration and password reset (anywhere else?).
 
- Do we need the addon? 
- There are configuration keys specified in the backend. 
- You can also turn off captcha using backend - should we follow that?
Backoffice > Base Commerce > Base Store > select your storefront
Properties tab > Captcha Widget Enabled
- Do we need API updates?
- Do we need threat modelling?

**Comment by Zeyber** [comment]
**Captcha Pages**
- Login
- Registration
- Checkout
- Product Reviews

**Captcha Component**
```
<cx-captcha
	()>

**Comment by meeque** [comment]
As discussed on other channels, this issue cannot be fully solved by Spartacus alone. This is because a reCaptcha must always be validated on the server-side. In this case it means that the underlying SAP Commerce OCC API needs to support reCaptcha validation first. 

SAP Commerce OCC does not support that yet, but respective changes are planned. Progress can be tracked at [RAY-405](https://jira.hybris.com/browse/RAY-405), but that is not publicly accessible.
