### ISSUE TITLE
[Xiaomi/Chrome] - Delivery info topics should align vertically

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#3483]
Delivery info topics on FAQ page should align vertically but instead are inline: 

![image](https://user-images.githubusercontent.com/11735817/60444864-4f021800-9c1e-11e9-8ea8-80a672039af1.png)

**Comment by Zeyber** [comment]
QA: This does not appear to be fixed.

![image](https://user-images.githubusercontent.com/11735817/83410441-b7510f00-a416-11ea-8c5f-db726f179d8a.png)

**Comment by Xymmer** [comment]
Reopening because we think it was merged into 2.0 too late and now must be added to 2.1 BUT it's a breakin change so needs Theme For Minors...
Mikel: Check release branch to see if it made it into 2.0.
If so great, just close this ticket.

If not, revert the merge and then we'll hold this one until TFM is available and then we add it there.

**Comment by Xymmer** [comment]
it made it! closing
