### ISSUE TITLE
[safari][iphone] Can't click the buttons in the bottom of the screen

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#3504]
When you touch area in the bottom of the screen in your website, the Safari's bottom menu pops up instead of triggering DOM event in the website. It can be frustrating especially when you want to click an Action Button in there and you cannot scroll down anymore - i.e. in modals of address verification or "added to cart" modal in *iPhone SE* (which has a relatively small screen).

Other websites also suffer from it, it's not only a problem of Spartacus. More details here: https://www.eventbrite.com/engineering/mobile-safari-why/

As a workaround maybe it will suffice to ensure enough bottom margin in the modals for mobile?

**Comment by developpeurweb** [comment]
Seems like this is **no longer an issue** when tested with mac **Simulator** + `dev-com-3` having the latest `develop`. Although, it needs to be retested on a **public instance** with the latest `develop` changes since the Mobile Safari version won't allow bypassing the privacy alert (even in "private" mode).

**Comment by giancorderoortiz** [comment]
Retest with Safari in public instance as well on iphone7 device. 
Test successful. 
Able to interact with buttons at bottom of screen in safari as expected.
