### ISSUE TITLE
[Discussion needed] Searchable selects in whole application

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#3652]
Regarding to Radhep's https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3469#issuecomment-509232764 we need to think about adjusting searchable selects everywhere,

**Comment by KateChuen** [comment]
- On Title (on both address book page and personal details), I am only able to get the first result by typing a letter. Typing the same letter again doesn't focus on the next option. For eg, if I type M, it will go to Mr, typing M again doesn't go to Mrs, Miss etc. The focus will stay on Mr.
- Same thing with Payment cards list. Perhaps these will be fixed in this ticket when they'll make all the dropdown menus consistent.
