### ISSUE TITLE
[ON HOLD] Include smartedit webApplicationInjector.js in schematics

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#3805]
We need to resolve legal/security issues with `webApplicationInjector.js` file first:
- what's the licence of this file, can we change it?
- should we cover it in our security guidelines/checks?

**Comment by Xymmer** [comment]
talking to Petra about feasibility of publishing sap commerce webappinjector file, which currently is under license in commerce suite only

**Comment by Xymmer** [comment]
Existing header is:
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.

The new header:
* Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file (https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/LICENSE).

**Comment by tobi-or-not-tobi** [comment]
I'd rather not include this as part of schematics, as I believe we need to change the approach here.
instead of making the import a blocking JS resource in the application, I rather make it configurable, and load it in a singleton service. We do this similar in the qualtrics integration. The main reason for this is that we don't like to load this in production. If we make the import part of the index.html, we basically need a public app and a non-public app. This makes deployments unnecessary complicated. The alternative is that the injector JS file is always loaded on production builds.

**Comment by artem-zur** [comment]
> I'd rather not include this as part of schematics, as I believe we need to change the approach here.
> instead of making the import a blocking JS resource in the application, I rather make it configurable, and load it in a singleton service. We do this similar in the qualtrics integration. The main reason for this is that we don't like to load this in production. If we make the import part of the index.html, we basically need a public app and a non-public app. This makes deployments unnecessary complicated. The alternative is that the injector JS file is always loaded on production builds.

Hi guys! Any updates on it ?

**Comment by marlass** [comment]
In 3.2 we released `@spartacus/smartedit` as a standalone package containing the Smartedit integration with spartacus.

In this package under `assets` directory we ship `webApplicationInjector.js` file.

Additionally this package have schematics setup. When you run `ng add @spartacus/smartedit` it will configure integration in your application and add to `angular.json` assets section of your application build glob that will copy `webApplicationInjector.js` file when you build application.
![image](https://user-images.githubusercontent.com/6259079/115858456-456b2500-a42f-11eb-879f-f8d5a7f36f52.png)
