### ISSUE TITLE
Export SiteContextUrlSerializer to make ability to provide custom UrlSerializer

### ISSUE THREAD

**Issue by antshater** [SAP/spartacus#3940]
We try to write custom UrlSerializer, using spartacus base logic inside, and faced with issue - importing class by unstable alias

## Environment Details

- Spartacus:  1.0.0

## Steps to Reproduce
try to export SiteContextUrlSerializer

## Observed Results

need to be impoted like this
import { ɵei as SiteContextUrlSerializer } from '@spartacus/core';

## Expected Results
ability to import normal way like
import { SiteContextUrlSerializer } from '@spartacus/core';

**Comment by antshater** [comment]
I thought again - maybe exporting of SiteContextUrlSerializer is too concrete, best way is make ability to decorate Spartacus url handling logic any way - so it will be more flexible to use

**Comment by Platonn** [comment]
@antshater could you give some use case of extending the logic of the `SiteContextUrlSerializer`?

**Comment by antshater** [comment]
> @antshater could you give some use case of extending the logic of the `SiteContextUrlSerializer`?

We use it for customizing spartacus routes for removing trailing slash in end of route for migrating from old version of site and by seo requirements, also it could be helpful for users who also migrating from another shops and has indexed routes prefixes or suffixes or whatever

**Comment by Platonn** [comment]
Thanks for the explanantion. Let's export it together with its depenency `SiteContextParamsService`

**Comment by sumanth-reply** [comment]
Is there an alternative solution to implement/change this in older version (2.0.x)? 

I have a requirement where when used with custom context this is causing issue. 
for eg: when visiting a site with `/de-DE` it works but the same fails when visiting with `/de-de`. The issue comes down to 
```
    urlExtractContextParameters(url) {
        const [, urlPart, queryPart] = url.match(UrlSplit);
        const segments = urlPart.split('/');
        if (segments[0] === '') {
            segments.shift();
        }
        const params = {};
        let paramId = 0;
        let segmentId = 0;
        while (paramId < this.urlEncodingParameters.length &&
            segmentId < segments.length) {
            const paramName = this.urlEncodingParameters[paramId];
            const paramValues = this.siteContextParams.getParamValues(paramName);
            if (paramValues.includes(segments[segmentId])) {
                params[paramName] = segments[segmentId];
                segmentId++;
            }
            paramId++;
        }
        url = segments.slice(Object.keys(params).length).join('/') + queryPart;
        return { url, params };
    }
```

where paramValues are always `[de-DE, en-DE]` and hence the lower case letters fails. I think adding lowercase to the params will solve it but would be cleaner if we could custom serialize it

**Comment by Platonn** [comment]
@sumanth-reply I'm not sure I understood your requirement. Would you like to allow for both lowercase and uppercase locale context in the URL?

The SiteContextUrlSerializer will be made public in 3.4. In earlier versions you need a [workaround](https://stackoverflow.com/questions/66871919/how-to-use-private-api-of-the-spartacus-library/66871920#66871920) to import it from private API.

**Comment by sumanth-reply** [comment]
Hi @Platonn , 
not allow but *match*. 
So if we are using `custom` context and the context is `../de-DE` but if a user tries to use the site with `de-de`, we want him to be redirected to `de-DE` or matched (case insensitive) by changing  `if (paramValues.includes(segments[segmentId])) {` part of the code. Otherwise the current behaviour is the url becomes `.../de-DE/de-de` and since `de-de` path(or page) does not exist, it fails with 404 page.

My current solution is to generate additional custom context and to get a segments match. If this was exported, I could customize it to include case insensitive.
