### ISSUE TITLE
Add one cart configuration, which can decide whether cart merged or not when user login

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#4154]
Currently, in SPA, if there is an anonymous cart, when user login, we do cart merge (merge the anonymous cart into user's latest cart). 

We can add a configuration, so that customer can config whether do the cart merge when user login, or make the anonymous cart become the user's active cart.

To make the anonymous cart become user's active cart, dispatch this:
```
new CartActions.CreateCart({
            userId: payload.userId,
            oldCartId: payload.cartId,
            toMergeCartGuid: undefined,
          });
```

**Comment by Platonn** [comment]
Let's say user has a pending cart "A". Later on he comes back, add something to the cart and logs in with **creating** new cart "B". Then we should carefully consider what to do with the cart "A". Scenarios:
a) user completes the checkout with cart "B" and he locally he gets undefined cart id. But somewhere there in the backend database there is hanging the cart "A"?
b) user has been all the time logged in on his mobile device holding cart "A". Then he will have different carts on different devices

**Comment by Xymmer** [comment]
@WeizhengSap @marlass still need this ticket?

**Comment by marlass** [comment]
There are 3 options for handling carts on the login:

### 1. Merging anonymous cart into user cart (which we do)
**Pros:**
- consistency on different devices (everywhere we have the same cart and it is synchronized on refresh across all devices)
- there is always only one active cart associated with the user

**Cons:**
- multiple users using the same device can mess with each other carts (UX). Eg. user 1 adds something to the cart and leaves the cart. Later user 2 wants to quickly buy something. Logs in and see strange items in cart (from user1).

### 2. Using anonymous cart as user cart
**Pros:**
- on login you are not surprised by some old items left in the cart

**Cons:**
- same cons for multi-user device as for merging cart (even worse, because you only see other person items in your cart)
- you have multiple active carts (different cart on each device)
- carts will be automatically restored when you complete one order (older active cart will become current active)
- very hard to reason about and program this reliably

### 3. Dropping anonymous cart and switching to cart that is associated with the user
**Pros:**
- you won't see items added by a different user in cart after login (multi-user device)
- always only one cart is active
- the same cart on every device

**Cons:**
- you drop the current cart content (often user adds something to the cart and only login for checkout - needs to add these items once again)

In terms of implementation and API usage solutions, 1 and 3 are fairly simple. We could even allow the user to decide what he wants to do with the current cart (merge it to his cart or drop it).

Switching between option 1 and 3 with configuration can be done. Option 2 I would say is way to complex to implement by us. End developers can replace the merge behavior if they would like such behavior.

@Xymmer if there is someone from outside interested with other behavior than merge we can do it. Otherwise we can close it.
