### ISSUE TITLE
Update smartEdit integration (webapplicationinjector)

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#4304]
Spartacus is running an older version of the SmartEdit webapplicationinjector, which causes some issues: https://jira.hybris.com/browse/CMSX-9177. We should update to the latest script to ensure we don't run into bugs which have been fixed already.

**Comment by CarlEricLavoie** [comment]
given that SmartEdit is loading the storefront (in this case spartacus) as an iframe, couldn't SmartEdit add the script themselves similarly to how tag manager work? Add a reference to the SmartEdit domain with their version of the webapplicationinjector. 

Otherwise, customers using older version of SmartEdit with Spartacus might not be able to use the webapplicationinjector to you'll be providing.

**Comment by tobi-or-not-tobi** [comment]
@CarlEricLavoie it's a good idea, although I'd do it slightly different. We could implement a small post message API for SmartEdit, that SmartEdit could use to inject the full webapplicationinjector code. That would be really smooth for the integration, as (1) only when needed the code is injecter, (2) there's like you suggested no mismatch with the version and (3) there's no effort for the customer to worry about the script. 

We need to carefully design it to ensure it's not a security breach to inject any code, and we need to validate with the SmartEdit team whether the injector can be loaded like this (from an async / timing perspective. 

I'll start the discussion.

**Comment by tobi-or-not-tobi** [comment]
FYI https://jira.hybris.com/browse/CMSX-9396
