### ISSUE TITLE
Item's long name is overflowing in item price column on review page

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#4517]
**Environment Details**
Spartacus: Release 1.1.1 
Browser: Chrome
Device: mac
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
Add a product with a long name to cart.
Proceed to checkout

**Actual Result*
On the order review step, the item's name is overflowing in the "Item Price" column.

![Screen Shot 2019-09-11 at 1 09 03 PM](https://user-images.githubusercontent.com/45409515/64719413-32902080-d496-11e9-8b39-0ddb43a7f876.png)

**Comment by KateChuen** [comment]
Also happens on the cart page in tablet view:
<img width="390" alt="Screen Shot 2020-04-01 at 5 57 40 PM" src="https://user-images.githubusercontent.com/45409515/78191178-7a32c580-7443-11ea-96f6-ccb5c514af5f.png">

**Comment by developpeurweb** [comment]
This can only be temporarily fixed, and the best way is to allow the `cx-name` tag to be constrained by the parent Bootstrap column classes throughout media queries, otherwise, we'll have to get into micro-fixing every scenario and media query. This is yet another reason for refactoring simulated tables, to be followed up in GH-7312.

![Screen Shot 2020-04-20 at 4 56 16 PM](https://user-images.githubusercontent.com/15113219/79799402-65519f80-8328-11ea-93e0-8d40521c3bba.png)

**Comment by developpeurweb** [comment]
This can only be temporarily fixed, and the best way is to allow the `cx-name` tag to be constrained by the parent Bootstrap column classes throughout media queries, otherwise, we'll have to get into micro-fixing every scenario and media query. This is yet another reason for refactoring simulated tables, to be followed up in GH-7312.

![Screen Shot 2020-04-20 at 4 56 16 PM](https://user-images.githubusercontent.com/15113219/79799402-65519f80-8328-11ea-93e0-8d40521c3bba.png)

**Comment by KateChuen** [comment]
Tested on dev10
✅chrome
✅safari
✅firefox

✅Tablet
<img width="426" alt="Screen Shot 2020-04-23 at 11 11 34 AM" src="https://user-images.githubusercontent.com/45409515/80115820-366b4180-8553-11ea-98bd-116381d03f87.png">

✅Desktop
<img width="1213" alt="Screen Shot 2020-04-23 at 11 09 57 AM" src="https://user-images.githubusercontent.com/45409515/80115828-39fec880-8553-11ea-9270-b90c60eefa5c.png">
