### ISSUE TITLE
Wrong Message When Token Expired And Adding to Cart

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#4640]
**Steps** 
1. Enable ASM feature.  (This is optional, as it happens without ASM as well. See below comments)
2. In backend, set the following properties and restart 
oauth2.accessTokenValiditySeconds=60
oauth2.refreshTokenValiditySeconds=120
3. Navigate to Storefront with ASM enabled. 
4. Login as ASM agent. 
5. Enter a registered user email (attach to account). 
6. Search for any product (which has stock). 
7. Navigate to product details page. 
8. Wait oauth2.refreshTokenValiditySeconds + 10 seconds. 
9. Click on Add to Cart button

**Expected Results:** 
9. Operation fails because of timeout. 
9.a. User is redirected to login page. 

**Actual Results:** 
9. An additional error message saying product was already in cart is displayed. ❌ 

![Screen Shot 2019-09-18 at 12 08 34 PM](https://user-images.githubusercontent.com/46171897/65165813-827a6480-da0d-11e9-9212-8012f6a88ede.png)
![Screen Shot 2019-09-18 at 12 09 03 PM](https://user-images.githubusercontent.com/46171897/65165814-827a6480-da0d-11e9-82b7-c2620faa6b4e.png)

**Comment by giancorderoortiz** [comment]
Issue also happens without ASM

![Screen Shot 2019-09-18 at 12 33 58 PM](https://user-images.githubusercontent.com/46171897/65167502-b4d99100-da10-11e9-94cd-d4523df42415.png)

**Comment by plabadie** [comment]
This looks like a behaviour unrelated to asm. Please reproduce on the develop branch.

**Comment by giancorderoortiz** [comment]
Unable to force session timeout. 
@tobi-or-not-tobi, @Xymmer is session timeout being kept alive beyond refresh token validity? 
Using: http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/

**Comment by janwidmer** [comment]
The same behaviour also happens, when it was not possible to add the product to cart due to an error in the backend, e.g. `CommerceCartModificationError`:

![image](https://user-images.githubusercontent.com/3381820/115398047-05b1fc80-a1e7-11eb-8eb6-89f9007d91b8.png)

This correctly triggers the "Add Entry Fail" Action, which just seem to do nothing then..
![image](https://user-images.githubusercontent.com/3381820/115398362-5c1f3b00-a1e7-11eb-8555-013e35897dc0.png)

As far as I have seen in the component `AddedToCartDialogComponent`, the title if statement seems to evaluate to the "Update" Case and as there is no valid cart entry, the title is the only thing which is displayed. 

It seems, that the component is missing some error handling..

I have solved it by adding the error handling in the `AddToCartComponent`:

```
this.events.get(CartAddEntryFailEvent).subscribe(() => {
	this.modalRef.dismiss();
	this.globalMessageService.add({ key: 'addToCart.error' }, GlobalMessageType.MSG_TYPE_ERROR);
});
```

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/3442

**Comment by giancorderoortiz** [comment]
I see the same behavior as in #3442. 
Issue not related to ASM as Patrick mentions above. 
I see correct error message indicating that session has timed out. Hence, closing this ticket. 

![Screen Shot 2021-06-20 at 6 58 18 PM](https://user-images.githubusercontent.com/46171897/122690820-a4fc6b80-d1f9-11eb-8a38-01aeff538a73.png)
