### ISSUE TITLE
<dev doc> Update release process to include latest release thinking e.g. 'next' instead of betas or rc's, review the overview, top-to-bottom update

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#4925]
https://wiki.hybris.com/pages/viewpage.action?spaceKey=spar&title=Release+process
Also is there an external doc that has to be updated?

Preliminary pass (merge https://wiki.hybris.com/pages/viewpage.action?pageId=467247626 and https://wiki.hybris.com/pages/viewpage.action?spaceKey=spar&title=Release+process)
- [x] Gil

> Gil note: Documents updated (not merged) here: [https://github.com/SAP/cloud-commerce-spartacus-storefront/releases]

First pass: 
- [ ] Miro
- [ ] Caine
- [ ] Michal

Then 
- [ ] Marcin
- [ ] Louis
- [ ] Gil
- Bill wants to read it

**Comment by Zeyber** [comment]
`Regression tests are run to QA the release.` should this be changed to say all tests?

**Comment by mirkosoft** [comment]
Nice checklist which I followed during last release:
https://www.notion.so/Releasing-libraries-34f7e1a0b082477e827e2829581b4ce7

- For the spartacus-installation script please ensure you're running it from the `/data/hybris/spartacus-installation` dir (in the home dir there is a link to it and if you just cd to link script will break).
- the above script has some "hardcoded" stuff in the `files` directory - in case of any troubles check whether something is mismatched due to spartacus code updates
- you can run `yarn generate:docs` on your local machine
- GITHUB_TOKEN env should be set to proceed with `release-it`
- `release-it` also can be run off local; `npm run release:assets:with-changelog` replace assets for the other 3 libs. Also use npm not yarn for release-it because yarn will ask you to authenticate a bunch of times

Still not sure what version number is going to be by the next release, also I don't feel comfortable with how (what) should be QA'ed currently and what exact command is for running test with the same way is in the pipeline.
