### ISSUE TITLE
Change links to plain underline

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5171]
For Caldyon theme. 

The current visual spec has regular and action links. Action links are uppercase, both are bold.
<img src=https://user-images.githubusercontent.com/4998145/67577370-58077f80-f70e-11e9-870c-54a4fbc6fe1a.png width=200 />

To reduce their importance, make them easier to read, and minimize localization/layout issues, let's make them both plain and Title Case. 

Like this example:

<img src=https://user-images.githubusercontent.com/4998145/67577713-07dced00-f70f-11e9-8181-f41de5710565.png width=200 />

The important thing for me is that the person browsing knows it's clickable.

Under the hood it's still important to tag them differently so that customers can make a visual distinction if they wish.

**Comment by Manurod2018** [comment]
"Classic" links and action links are defined as two different things in the guidelines: "Classic" links lead you to content off the page, while action links led to an action: for example, deleting an item from your card. Those are Uppercase and bold so that they stand out among content.

If under the wood we are tagging them differently, why hiding it on the front-end?
Can you provide some examples (screenshots) where this is a problem with localization/layout?

**Comment by Xymmer** [comment]
For our storefront I'd like to reduce/minimize use of bold unless necessary, as I find it grabs too much attention for no reason. Also, all uppercase is hard to read. It's not really necessary to differentiate visually although we'll continue to do so for the sake of customers that might like to. Let's proceed with the change please.
