### ISSUE TITLE
Avoid usage of uppercase, with exceptions

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5172]

**Comment by Manurod2018** [comment]
I agree that we have to be very conservative in capitalizing.
However, it does make sense under some circumstances. From a visual design perspective, all caps are fine in contexts that don’t involve much reading, such as headings, and menus. In other places like product titles or more lengthy text, we use lowercase. 

The use of uppercase is defined in the guidelines and used where it makes sense, in order to increase contrast or create a distinct style between two pieces of content. It's part of the organizational system to add structure and visually reinforce hierarchy.
Those areas are:

Main menu
Main sections of the menu on mobile
Titles of sections on the left menu (faceted search) 
CTA
Tabs
Action links

**Comment by Xymmer** [comment]
Adhering to hierarchy should take a backseat to readability, ease of parsing, and reduction in usage of space. It's especially ugly in mobile. Let's start with everything lowercase and make exceptions based on need (of which I don't see any right now). Proceed with the change please.
