### ISSUE TITLE
Test when customer ID is not standard

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5451]
We're asked to check if Spartacus breaks, if we use a non-standard customer ID, like 0001 instead of the usual format:
699a4fb1-70e1-428f-a029-902950538853

Using impex, add a user who has an ID of 00001 and see if Spartacus complains, then let Bill now and he'll get back to the people who are asking. Try checking out, change password, etc.

**Comment by KateChuen** [comment]
Tested on dev10. Imported customer 0001 by impex. 

- Customer cannot login from the login form, because of the form validation done in the email input field.

- We can however start the customer's session through asm.
<img width="1432" alt="Screen Shot 2019-11-19 at 1 47 45 PM" src="https://user-images.githubusercontent.com/45409515/69177545-b9382e00-0ad5-11ea-8842-23c983efade9.png">

- Through asm, customer can update his information, for eg, address, personal details, password etc.
<img width="836" alt="Screen Shot 2019-11-19 at 1 48 54 PM" src="https://user-images.githubusercontent.com/45409515/69177445-8a21bc80-0ad5-11ea-8820-fb2c1a1c9747.png">

- Through asm, customer cannot place any order because he cannot even add a product to cart. We can an error that the product isn't unique. 
<img width="703" alt="Screen Shot 2019-11-19 at 1 50 35 PM" src="https://user-images.githubusercontent.com/45409515/69177447-8d1cad00-0ad5-11ea-8f86-ecad0be70755.png">
