### ISSUE TITLE
Checkout validation: stock, price, promotion (needs spike, then we'll prioritize)

### ISSUE THREAD

**Issue by RafaelPaz-Keyrus** [SAP/spartacus#5452]
There is no stock validation during the checkout process.

## Environment Details
- Spartacus: 1.0.3
- Hybris: SAP Commerce Cloud, 1905

## Steps to Reproduce
1 - Create a customer account and login
2 - Add a product to the cart
3 - Remove the stock from the product in the backoffice
4 - Proceed to checkout

Result:
We can proceed through the whole checkout process, till the place order, where there is a validation.

Expected:
We shouldn't be able to proceed to the checkout page.

**Comment by Xymmer** [comment]
Check also if this problem occurs at different points:
e.g. after adding to cart
- remove stock and show cart
- show cart, remove stock, go to checkout
- go to checkout, remove stock after step 2...
- etc.

**Comment by Xymmer** [comment]
#5652 looks related, maybe think about that one with this one

**Comment by LTiger14** [comment]
At the moment Spartacus lacks stock awareness once the item is added to the cart. Like mentioned in the issue description, the only validation happens when placing the order.

This means that once an item is added to the cart we **never** make sure it is still in stock until we place the order. This is bad UX especially if the product went out of stock at a much earlier time.

After spiking on the topic I came up with the following changes that would provide a solution to the problem:

1. Adding some logic to check if the cart contains a product that is out of stock in `cart-not-empty.guard`.

Every checkout step is guarded by the `cart-not-empty guard` which makes sure the cart is not empty. We could add some logic to check if the cart contains a product that is out of stock or has a stock inferior to the entry's quantity in the cart inside the guard or create a new guard.

This will prevent a user from progressing through the checkout if one of his items is out of stock or has an insufficient quantity.

2. Fix the `isProductOutOfStock` in `cart-item.component`

`cart-item.component` already has a method to check if the product in the cart is out of stock but this method does not work at the moment. When fixed, it displays a message that tells the user this product is out of stock (the translation for the error is missing).

3. Add some logic to `cart-totals.component` to disable the proceed to checkout button if an item in the cart is out of stock.

#### Caveats

- The solutions I proposed above still faces a limitation caused by the asynchronous nature of Spartacus. Spartacus will only fetch the cart at certain moments and generally uses the data store in memory. 
Therefore with the right timing it is possible to bypass a few of the validation steps I mentioned above but never all of them. There is no real solution for this.

- In addition before starting on a definitive fix we would need more input on the expected behavior of Spartacus for this issue. Specifically, what should happen when de product goes out of stock in different scenarios (checkout, browsing, etc.)

**Comment by psmul** [comment]
All sugestion will be taken into account while implementing cart validation. For progress please follow board:
https://github.com/SAP/spartacus/projects/135#card-58698035
