### ISSUE TITLE
Update sonar rules for after 2.0

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5622]
Sync the Javascript and Typescript profiles you are using in  https://sonarcloud.io/dashboard?id=sap_cloud-commerce-spartacus-storefront, with the profiles in use in https://sonar-ec.hybris.com/profiles
 
- [x] Gil to investigate feasability
- [ ] someone does it (not 1.4!!!!)

**Comment by hackergil** [comment]
We cannot customize rules in SonarCloud (since it is a service). That said, we can compare the existing rules in SonarCloud with the ones applied in sonarQube and enable more rules accordingly. Also, our lint and prettier rules have to be taken in account for this.

**Comment by hackergil** [comment]
After updating rules in our typescript profiles, we get the following:

- 43 major issues (vs 16, before)
- 1 new security hotspot
- 2.5K new lines to cover

Out of those 43 major new vulnerabilities. All of them are related to the following rule:

"Unexpected template string expression"

This is because we have some strings (on the configurations for the request URLs) that pass a string as a template (instead of a template itself) which later on is evaluated as a template. We can discuss if either disable the rule or change them all to templates. Once that is done we can switch to scan with the new profile by default.

**Comment by hackergil** [comment]
Assigned to @Xymmer to be discussed.
