### ISSUE TITLE
Get rid of return subscription from method setActive in site-context facade

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6082]
Returned value is unnecessary and unused
- [x] base-site.service
- [x] language.service
- [x] currency-service

**Comment by bgambocjaviniar** [comment]
Removing `team/asterix` label as I was told to take this ticket

**Comment by bgambocjaviniar** [comment]
PR: GH-9779

QA steps:
- make sure Spartacus starts and test overall flow (in general)
- run the e2e suite to make sure nothing breaks. (As long as the result is the same as our current e2e's statuses) 

----NOTE
running two jenkins build towards this PR (will post results below when it's ready) 
- https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/458/
- https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/459/

**However, do note sometimes the pipeline will hang at times as it is currently doing in our main pipeline due to Cypress's retry mechanism when a test fails**
