### ISSUE TITLE
Duplicated outlets

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#6135]
How to reproduce:
- register outlets in page/component template
- go to that page or page containing modified component
- go to page (client side navigation) that was targeted with outlet
- you should see registered outlet there
- go to previous page (client side navigation)
- go again to page targeted with outlets (client side navigation)
- you see duplicate outlets

Desired behavior:
- the same outlets are not duplicated

First steps that can be implemented:
- inform users where they should declare outlets

**Comment by tobi-or-not-tobi** [comment]
@marlass was this introduced with #5942?

**Comment by marlass** [comment]
> @marlass was this introduced with #5942?

It was discovered while working on this bug. Issue is not with rendering, but adding the same outlets to outlets store. Probably it was introduced with stacked outlets (but I didn't check that assumption).

**Comment by Platonn** [comment]
We need to discuss whether we the `cxOutletRef`s should be declared once or could be added in the run time.
Declaring cxOutletRef in the root component is done once.
Declaring cxOutletRef in some nested component which can be destroyed and re-created can lead to declaring an outlet's view with a delay (when wrapped with `async` pipe) or can be declared many times (whn wrapped with flickering `*ngIf`). 

We should ensure that we don't add again this cxOutletRef to the stack if it was added before.

Proposed solution:
Unregister the custom view declared with cxOutletRef when the directive is destroyed (in its `ngOnDestroy`).

**Comment by tobi-or-not-tobi** [comment]
The same behaviour is experienced in case the standard product uses outlets. Not only is the template registered whenever the host component is recreated, it also affects customers if they introduce a custom outlet. 

While you could indeed use a lifecycle hook to explicitly remove an outlet template, we can also avoid adding it in the first place. We're preparing a PR that introduces to skip registering a template if there's already one registered. 

Since _stacking_ is default, we need this explicit notion. We can advertise this to customers in case they use outlets in components.

**Comment by Platonn** [comment]
This issue affects tables with outets used for my-company, so chaning milestone to 2.1 (must)
