### ISSUE TITLE
Cannot add more than qty 1 on pdp but can do so on added to cart modal

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#6180]
**Environment Details**
Spartacus: 1.4.x branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
1905 suite, with Spartacus recipe, with oms, 2005 occ extensions

**Steps to Reproduce**
- Go to pdp of product 443175
- Try to change the quantity to for eg, 40 -> Cannot change qty.
- Add qty 1 to cart
- On the added-to-modal cart, change the qty to 40.
- Place order.

**Actual Result**
On pdp, we cannot add more than 1 of that product.
But on added-to-cart modal, we can. 

After the order is placed, the order status remains _In Progress_ with the consignment status being _Pending_.

<img width="1034" alt="Screen Shot 2020-01-20 at 1 52 31 PM" src="https://user-images.githubusercontent.com/45409515/72750949-3cd0d280-3b8c-11ea-8bbd-7d0fe52422ef.png">

**Comment by Xymmer** [comment]
some additional info:
it looks like that particular product is in stock but no stock quantity is returned:
   "stock": {
      "stockLevelStatus": "inStock"
   },
Looking at stock status, every warehouse is 0 except for **warehouse_w**, which has 2. Changing that to 0 doesn't affect how the product is stated as in stock.

My first thoughts:
- in spartacus we have to figure out what we should be doing with a product that has stockLevelStatus=instock but has no stock level. I think we have to trust stockLevelStatus because it's possible some systems won't return total stock. but to be discussed more with Tobias.
- it looks like the PDP and add to cart modal have two different behaviors, let's align them.

**Comment by Xymmer** [comment]
assumption is, if in stock, and stock level not known: can add as much stock as you want

**Comment by kacperknapik** [comment]
Fixed in #7339
