### ISSUE TITLE
[ON HOLD] Configurable share link for product page with extensibility options

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#6249]
This task is to add social share links to the product page
- configurable
- clicking the link(s) creates the correct share call(s)
- we define a few of the popular ones
- doesn’t use an external service

Steps:
1- Design the feature, look at other sites, talk to Bill
2- Go over architecture with Stan or Tobias
3- Implement

Ideally the links would be defined in the backend, i'm not sure that's possible though.

**Comment by tobi-or-not-tobi** [comment]
@LLink-dev as discussed I give you a couple of pointers for sharing. 
FYI @Xymmer 

**Share with social platforms**
Sharing links with social platforms is done by presenting a URL to the social platform. The crawler will then visit the given URL in order to fetch the content from the page. 

For an ideal setup, various parts are required: 
1. the shared URL should be public available to the social platform, as it will visit the URL; this will not work for a non-public site (i.e. on local develop)
2. the shared page should be indexable, meaning that there should be real content for the give URL; note that by default a SPA will not contain this as the DOM is created in at runtime, which is one of the reasons we need an SSR server (see https://sap.github.io/cloud-commerce-spartacus-storefront-docs/server-side-rendering-in-spartacus/). The crawler will crawl the given page source, to look for content. 
3. the DOM can provide very specific html to steer the social platform. If nothing provided, the crawler will evaluate the DOM to retrieve the page title (title element), the main image, a description, etc. You can provide specific info for the platforms, using meta tags. Facebook started with Open Graph (i.e. `og:title`), Twitter started with a similar standard (i.e. `twittter:description`), while it will fallback to `og`. See https://sap.github.io/cloud-commerce-spartacus-storefront-docs/seo-capabilities for more info. 
4. Besides a semantic DOM and metatags, social platforms also understand *structured data*, which Spartacus supports as well (see https://sap.github.io/cloud-commerce-spartacus-storefront-docs/structured-data/)

You can test these crawlers by using dev tools, to name a few:
- https://developers.facebook.com/tools/debug/
- https://developers.pinterest.com/tools/url-debugger/
- https://cards-dev.twitter.com/validator

For a great experience, we should not launch the social platform URL, as it will move users away. Ideally, there's an inline experience, so after sharing the page, the user can continue with purchasing at the storefront. 

**Share with any**
PWAs nowadays are getting access to native sharing of pages with any application on a device. This is done by using native APIs from the device OS, using `navigator.share()`, see https://github.com/w3c/web-share. We should keep this in mind as a near-future feature. 

**Share any**
We should not hang up the share feature to a product, it's a page feature. All product related features are related to the content of the page (DOM, metatags or structured data). A generic share feature can be used on any page, so that each page (corporate, brand, category, campaign, listing) can be shared.
