### ISSUE TITLE
Sec Alert. serialize-javascript. Upgrade to version 2.1.1. XSS

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#6298]
The following security alert has been risen by github.

**Alert:**
https://github.com/SAP/cloud-commerce-spartacus-storefront/network/alert/yarn.lock/serialize-javascript/open

**Severity:**
moderate.
(Seems high impact)

**Request:**
Upgrade serialize-javascript to version 2.1.1 or later

**Motive:**
Affected versions of this package are vulnerable to Cross-site Scripting (XSS). It does not properly mitigate against unsafe characters in serialized regular expressions.

GHSA-h9rv-jmmf-4pgx

**Additional comments:**
If decision is to dismiss, please provide concrete justification for further assessment during peer review.

**Comment by giancorderoortiz** [comment]
@hackergil @tobi-or-not-tobi fyi

**Comment by tobi-or-not-tobi** [comment]
This is not a very big issue as it might seem to be. To begin with, the issue is not related to the application code, but is used in the background by the Angular CLI. It will therefor not affect build artefacts which are distributed to npmjs.com.

Furthermore, the issue is also [not affecting node.js applications](https://github.com/yahoo/serialize-javascript/security/advisories/GHSA-h9rv-jmmf-4pgx), and therefor doesn't affect the CLI.

It does look bad, and keeps bugging people to investigate. It would therefor be good to upgrade our repo to the latest angular 8.3.x version (as it's fixed already in CLI 8.3).

**Comment by tobi-or-not-tobi** [comment]
@giancorderoortiz I've removed the critical and security labels, see ^^ for the reasoning.

**Comment by LTiger14** [comment]
This issue is fixed on develop with Angular 9
