### ISSUE TITLE
Apparel: It keeps the previous header when the category has no results

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#6402]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP

**Steps to Reproduce**
- Go to apparel uk storefront: http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP
- Go to mobile view
- Click on the hamburger menu -> Brands -> Shop all Brands.
- Now go to Snow -> Shop all snow

**Actual Result**
The previous header is still displayed. 
<img width="397" alt="Screen Shot 2020-02-04 at 4 25 07 PM" src="https://user-images.githubusercontent.com/45409515/73788728-8fed7c80-476b-11ea-944d-4ebb4146dd47.png">

Now if you go to let's say, Brands -> Shop all brands. It will display " 0 results for Snow" temporarily. Probably why it keeps the previous header.

<img width="375" alt="Screen Shot 2020-02-04 at 4 26 34 PM" src="https://user-images.githubusercontent.com/45409515/73788651-6a607300-476b-11ea-93d8-5de7554c4044.png">

**Comment by giancorderoortiz** [comment]
Still an issue?

**Comment by bgambocjaviniar** [comment]
> Still an issue?

yes

**Comment by bgambocjaviniar** [comment]
hotfix backend PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/185

You can see it affects electronics the same way as apparel. The breadcrumb is under the first banner in the SLR 'collection' category page

----
**Unless, we don't mind not following acccelerator, where the breadcrumbs are home > collections > collectionName
We can always make it home > collectionName using the page request**

reason for the hotfix of removing breadcrumbs from the page is not being able to differentiate whether this page is a category or a collection 'category' page.

- If we want to go the route above instead of the hotfix, please ping me to fix

**Comment by bgambocjaviniar** [comment]
QA:

use latest sample data 

- visit /apparel-uk-spa/en/GBP/c/snow and verify there's no more breadcrumbs
- visit /electronics-spa/en/USD/c/578 and verify there's no more breadcrumbs

**Comment by giancorderoortiz** [comment]
Requires infra upgrade for testing. 

Please inform next time when this type of sampledata upgrades are done so that infrastructure can be upgraded without causing interruptions to team.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-06-29 at 1 08 38 PM](https://user-images.githubusercontent.com/46171897/123840169-04ced280-d8dc-11eb-967d-0f9dbd70ac14.png)

ok
