### ISSUE TITLE
Anonymous Consents Form not scrollable

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#6546]
## Environment Details

- Spartacus:  Public Instance https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/
- Browser: Chrome and Safari
- Device: Mobile (iPhone 7) **Dev tools will not be able to reproduce this error**

## Steps to Reproduce
- On the front page, scroll all the way down and click on Consent Preferences.
- The form should pop up but you won't be able to scroll down to check the other options.

## Expected Results
Form should be scrollable

**Comment by bgambocjaviniar** [comment]
PR: GH-7432
maintenace PR: GH-7455 

will fix one or the other depending which one goes in first :)

**Comment by bgambocjaviniar** [comment]
QA steps:

Desktop:
- verify in a small viewport (witdth/height), we can scroll in any modal, such as add to cart or anonymous consent dialog, etc in *Safari*

Mobile (IOS):
- verify it is scrollable in chrome / safari (same step as above)

General:
- verify the footer has no extra margin-bottom on the cx-paragraph

**Comment by KateChuen** [comment]
Tested on dev3 (frontend), dev7 (backend).

✅Desktop -> Tested on chrome, safari and firefox.

❓Iphone -> Could not test on an iphone, could not access. I get "Safari could not open the page because the server stopped responding."
Louis tested it this way: 
_Technically I used my localhost pointing to the ccv2 backend. Also since I don’t have an Iphone I used the simulator in Xcode._

**Comment by Xymmer** [comment]
was able to check iphone, fixed
