### ISSUE TITLE
Continue button in payment method disabled even if payment method selected

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#6839]
## Environment Details

On develop

## Steps to Reproduce

- Create a new account
- Checkout
- Add a product to cart
- Checkout again
- On the payment method page it says the payment method is selected but the continue button is disabled

## Observed Results

On the payment method page it says the payment method is selected but the continue button is disabled

## Expected Results

Since the payment method is "selected" the continue button should be clickable

**Comment by qjimmy** [comment]
After a lot of investigation, the button is disabled when there is no payment method. Once the user adds a payment method but does NOT select it (the checkbox), the new and only payment method associated to the user's account is not selected on the second time the user checks out. _(It passes the first time user checks out since it brings user directly to order review page)_ 

It should select the only payment the user has by default

**Comment by marlass** [comment]
I will take care of that bug
