### ISSUE TITLE
Verify i18n related third party dependencies

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7173]
We should check if we should upgrade:

-    "i18next": "^15.0.6",
-    "i18next-xhr-backend": "^2.0.1"

before going to 2.0

**Comment by Platonn** [comment]
# QA steps:

## PREREQUISITES
### Build and pack libraries localy
1. `yarn build core:lib`
2. go **into** folowing folders and run `npm pack` **inside** there:
  - [ ] `dist/core`
  - [ ] `dist/storefrontlib`
  - [ ] `dist/assets`

### Create a fresh shell app
1. go to parent directory in relation to your spartacus repo
2. create a fresh shell app using `ng new`, i.e. `ng new test-app`
3. go **into** the new app (i.e. `cd test-app`)
4. install spartacus with SSR and baseSite `electronics-spa` using schematics:
   ```
   ng add @spartacus/schematics --ssr --baseSite=electronics-spa --baseUrl=https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002 --overwriteAppComponent=true
   ```
5. Schematics just installed npm-published spartacus for you. But you need localy npm-packed libs. So let's install them again, but from local folders. For example: 
   ```
   yarn add ../spartacus/dist/core/spartacus-core-2.0.0-next.3.tgz
   ```
   (assuming that `spartacus` is folder name of the spartacus repo; and suffix of the filename `spartacus-core-2.0.0-next.3.tgz` may vary depending on the version of spartacus).
   **Repeat it please for all 3 libraries:**
   - [ ] core
   - [ ] storefrontlib
   - [ ] assets

### Allow for insecure https in SSR
1. allow for insecure https calls in SSR to let it work with dev-com server - in the top of file `server.ts` of test-app (i.e. just under all `import`s) add a line:
  `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`

### Configure lazy loadable JSON translations
1. copy translation resources from `node_modules/@spartacus/assets/i18n-assets` to `src/assets`:
   ```
    cp node_modules/@spartacus/assets/i18n-assets src/assets/ -r
   ```
2. Configure in test-app's `app.module.ts` the path to JSON assets - replace in `i18n` config:
   from:
   ```
   i18n: {
       resources: translations,
   ```
   to:
   ```
   i18n: {
        backend: {
          loadPath: 'assets/i18n-assets/{{lng}}/{{ns}}.json',
        },
   ```

## TESTING in test-app
1. close all exising ng dev servers (especially running on port 4200)
2. start Spartacus SSR serve: `yarn dev:ssr` 
3. open application and verify that texts (i.e. in buttons) are translated
4. in the network devtools tab verify that translations are loaded from JSON files (i.e. verify there is a requires for `common.json`)
5. change language using language selector in top left corner of application and verify it's working
6. disable Javascript in your browser
7. refresh application and verify that texts are translated in the server-side rendered page (don't worry app layour looks slightly different - it's on purpose,  due to a mobile-first layour in SSR)
