### ISSUE TITLE
MediaService improvements

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7229]
We've seen various issues with the media service. Some of them are reported, some where mentioned during customer interaction. 

The main problem is that the media service is driven by breakpoints, which is actually wrong. The breakpoints are only taken the full screen into account, while media are often inside a smaller layout. With that setup, the `srcset` that is used in images aren't leveraged as much as we should. We should introduce a specific media configuration to map a so-called threshold to a media format (media formats are used in the backend to distinguish size-format for the same media). 
When the `srcset` is properly set on the img element, there's no longer the need for components to dictate a specific format, as the browser will handle the format based no the `srcset`. 

Another behaviour we've seen with new projects, is a mismatch of media formats in the backend and spartacus. This results currently in no media at all. This looks very bad and demotivates the dev. We should fallback to any of the available media in this case, by default the most optimised version or a random one if we can't figure this out. 

This ticket will fix several related bugs:  #6629, #5398, #5395

**Comment by tobi-or-not-tobi** [comment]
QA: 
- confirm that images show up everywhere as expected
- confirm that the different formatted images show up in the mobile vs desktop experience. It's important too hard refresh the window to benefit from the sized images. We do not explicitly render specific size in the current version, but leave it up to the browser to pick the right size. The browser decides on viewport, device (retina screen), etc. Going forward we will bring in explicit sizes.

**Comment by KateChuen** [comment]
Tested on dev10 on chrome, firefox, safari, on different viewports.

✅confirm that images show up everywhere as expected
✅confirm that the different formatted images show up in the mobile vs desktop experience. It's important too hard refresh the window to benefit from the sized images. We do not explicitly render specific size in the current version, but leave it up to the browser to pick the right size. The browser decides on viewport, device (retina screen), etc. Going forward we will bring in explicit sizes.
❌I noticed there's just an issue if upselling products are missing images, Opened ticket #7378
  ↪️✅This is now fixed in ticket 7370.
❌I found a product where the image isn't rendered, not sure if it's a data thing. (if I go to Digital Cameras -> Compact cameras. Then scroll down to product M340 -> we see the image on plp
Go to the pdp of that product -> no image displayed at all
Add to cart -> "Image coming soon" thumbnail
 ↪️✅This is now fixed in #7557. Now a "Image coming soon" is displayed on the pdp and cart page, add-to-cart modal etc.
