### ISSUE TITLE
Broken tabbing-order e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7517]

**Comment by giancorderoortiz** [comment]
I see the test still failing. 
See video and screenshots

![Tabbing order - tests do require user to be logged in -- Checkout -- Payment details -- should allow to navigate with tab key (billing address) (failed)](https://user-images.githubusercontent.com/46171897/85596539-ce4edf80-b617-11ea-9bb7-68be69fe33ed.png)


[screenshots.zip](https://github.com/SAP/spartacus/files/4826777/screenshots.zip)
[videos.zip](https://github.com/SAP/spartacus/files/4826782/videos.zip)

**Comment by giancorderoortiz** [comment]
Further comments: 
I don’t see the actual tab navigation happening. Instead I see the particular element is selected directly via a keydown event as implemented here:
https://github.com/SAP/spartacus/blob/c13f6fe53c947054490a269d8310848df9584539/projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/header.ts#L36

So if I’d like to tab into Accessories -> Color Films, I’d expect to see in this e2e test the following sequence:
Focus on Brands, then Digital Cameras, Film Cameras, Camcorders, Webcams, and eventually accessories. 
(Blue rectangle surrounding each navigation category)
Then trigger Spacebar keyboard event, which opens up Accessories category, and tabbing all the way to Color Films.

To me, as it stands, within the context of accessibility, this e2e test doesn’t suffice as it doesn't emulate what an actual user with physical disabilities would do.
@developpeurweb please review as well.

**Comment by giancorderoortiz** [comment]
@hackergil, @Xymmer This test is very long. It should be split up. It takes more than 6 minutes to run.

**Comment by giancorderoortiz** [comment]
A very interesting discussion about tabs in cypress : https://github.com/cypress-io/cypress/issues/299

**Comment by kacperknapik** [comment]
@giancorderoortiz 
1. Keydown event seen in `subCategoryTabbingOrder()` function is purely for focusing the first element. Otherwise, with your proposed solution - "following the whole sequence", the test would last 100 times more.
2. Tabbing test and aux-keys test both test navigation - first is tabbing through the navigation main categories, second is checking arrow keys etc - we decided to split that, again for the sake of time saving
3. Tabbing test checks tabbing order, there is no need to check the 'blue rectangle', we just check if the order of focusing elements is correct - also there is no optimal solution for checking 'blue rectangle', so we decided to drop it
4. `"it doesn't emulate what an actual user with physical disabilities would do"` - we check tabbing order, focus accessibility and auxiliary keys, doesn't matter what a disabled person would do, we got this covered. there is no scenario, these tests are not testing
5. tests were long-ish from the very beginning, and a11y was merged in February
6. Discussion that you've linked is about cypress lacking tabbing support, we read it before, there's nothing that interesting
