### ISSUE TITLE
Fix flaky order-history-orders-flow e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7522]
This test is currently part of flaky group. Check if it is still flaky, check if it is not to slow and if everything is fine introduce it into regression group (change `flaky-e2e-spec` extenstion to `e2e-spec`)

**Comment by giancorderoortiz** [comment]
The date format for German is not being applied causing the test to fail. 
This method call orderHistoryTest.checkCorrectDateFormat(); in order-history-orders test spec fails.
Assert expects day. Retrieves month. 

![Screen Shot 2020-06-17 at 11 09 59 AM](https://user-images.githubusercontent.com/46171897/84915729-2b341e00-b08b-11ea-876b-3076447a2e4b.png)

Gladiators team reported that date format change is indeed expected to happen, so I'll create a separate bug to address issue.

**Comment by giancorderoortiz** [comment]
I see some inconsistencies. 
When running the test in interactive mode, the test passes. Somehow cypress forces a date format change, which doesn't happen when an actual user changes the language.

**Comment by giancorderoortiz** [comment]
Cypress run: 
![Screen Shot 2020-06-26 at 9 15 56 AM](https://user-images.githubusercontent.com/46171897/85861039-b13c1d00-b78d-11ea-8bdd-a7e8c9d6b025.png)

**Comment by giancorderoortiz** [comment]
Manual run: 
![Screen Shot 2020-06-26 at 9 18 02 AM](https://user-images.githubusercontent.com/46171897/85861224-feb88a00-b78d-11ea-86ce-7ba47a055f1b.png)

**Comment by giancorderoortiz** [comment]
Issue https://github.com/SAP/spartacus/issues/7996 blocks this e2e test.

**Comment by hackergil** [comment]
I started making some progress on this ticket. There's a feature branch with some commits already but no PR yet. Here's what I found:

* There were some missing waits, which I've added (in a non-clean way, needs refactoring)
* When we place two orders on this test, WaitForOrderToBePlacedRequest cypress command seems to have an issue with asynchronicity. Sometimes it doesn't wait properly until both orders have been placed
* I don't think we need to do the checks at the beginning since the checkout page already does these verifications (going to the order history page after an order has been placed and checking that the order is there)
* I suggest an alternative method to place the orders before running this test to speed it up. After having a discussion with the team and also the previous team from OMS, there were a couple of suggestions:

1. Override OMS extension to make the order process flow more lightweight (remove some steps, such as fraud, consignment and so on)
2. Prepare an impex and import the orders that are ready before running the spec

**Comment by Xymmer** [comment]
passing as of oct2

**Comment by Xymmer** [comment]
This was marked as [BLOCKED by #7996] but #7996 is closed, but the test is still flaky

**Comment by hackergil** [comment]
This test was fixed several weeks ago. Closing.
