### ISSUE TITLE
Flaky applied-promotions e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7523]
This test is currently part of flaky group. Check if it is still flaky, check if it is not to slow and if everything is fine introduce it into regression group (change flaky-e2e-spec extenstion to e2e-spec)

**Comment by giancorderoortiz** [comment]
Default routing configuration is not being applied.
Trying to access product detail page with only product ID fails. (i.. 4200/electronics-spa/en/USD/product/1382080)

Will create separate ticket.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-06-17 at 12 54 08 PM](https://user-images.githubusercontent.com/46171897/84930708-b4555000-b09f-11ea-8702-86fa7d610696.png)

**Comment by giancorderoortiz** [comment]
Delivery-mode page has random load times. 
The content of delivery-mode page do not load, or may load after timeout. (i.e. standard shipping / priority shipping)
The issue is that it eventually returns with HTTP 200. 
This causes intermittent delays and random failures. 

Opened backend ticket: https://cxjira.sap.com/browse/C3PO-2396 for further review. 
Dev may want to force a reload upon failure. Further discussion needed. 

It's more likely to happen when starting out fresh with a brand new user.

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/8012
