### ISSUE TITLE
Flaky cart e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7525]
Evaluate if it is still flaky and fix underlying issue.

**Comment by giancorderoortiz** [comment]
Delivery-mode page has random load times.
The content of page do not load, or may load after timeout.
The issue is that it eventually returns with HTTP 200.
This causes intermittent delays and random failures.
Opened backend ticket: https://cxjira.sap.com/browse/C3PO-2396 for further review.

Dev may want to force a reload upon failure.

It's more likely to happen when starting out fresh with a brand new user.

**Comment by giancorderoortiz** [comment]
Related to #8012

**Comment by Xymmer** [comment]
passing as of oct2
