### ISSUE TITLE
[retry] apparel doesn't run out of the box for 2.0

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7826]
With 2.0 schematics, I can't run apparel out of the box.

The workaround right now is to add context settings to app.config:
```
context: {
        urlParameters: ['baseSite', 'language', 'currency'],
        baseSite: [
          'electronics-spa',
          'apparel-de-spa',
          'apparel-uk-spa',
        ],
        currency: ['USD', 'GBP']
      },
```

When I go to http://localhost:4200/ I get
http://localhost:4200/en/USD/

Doing the following gives me a 'not found' error:
http://localhost:4200/apparel-uk-spa/en/GBP/

Is it something we can fix in schematics or in sample data?
Or can we use context detection? http://apparel-uk-spa.local:4200/
(I tried that and get "Invalid host header" with hosts updated with *-spa.local)

**Comment by znikola** [comment]
The can mitigated with the new schematics options `language` and `currency`.
See this PR https://github.com/SAP/spartacus/pull/7833 and this docs PR https://github.com/SAP/spartacus-docs/pull/625 on how to use them.

However, this doens't fix the root cause.

**Comment by KateChuen** [comment]
I believe 2.0 was working ootb against 1905.
2005 was the issue.

**Comment by KateChuen** [comment]
Stan has a comment. Bill to follow up. Maybe will need to update docs.

**Comment by dunqan** [comment]
It supposed to work with either static config (workaround explained in the ticket) or with auto config (aka context detection).

Regarding: 
> Or can we use context detection?  (I tried that and get "Invalid host header" with hosts updated with *-spa.local)

It should work as described, but there is a limitation for development when using `ng serve` with not `localhost` only domain (that's why "invalid host header" error).

To make it work, it's required to run ng serve with `--disable-host-check` parameter, like this:
- ng serve --disable-host-check (for multisite)
- ng serve --host apparel-uk-spa.localhost (for apparel only)


And it's covered in docs:
https://sap.github.io/spartacus-docs/automatic-context-configuration/#local-development
