### ISSUE TITLE
[dupe] Smoke Currency e2e Spec Fails Against 2005 Backend

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7846]
**Describe the bug:**
Failure in cypress test execution of https://github.com/SAP/spartacus/blob/develop/projects/storefrontapp-e2e-cypress/cypress/integration/smoke/currency.e2e-spec.ts

**To Reproduce:**

1. Deploy 2005 CS backend. Spartacus recipe. (i.e. dev-com6)
1.a. Set spartacussampledata version to origin/release/2005/next
2. Adjust taxes in backoffice base store to US.
3. Deploy spartacus in localhost (develop branch or 2.0rc4)
4. Run currency spec in cypress.
4.a. Make sure it uses new api routing /occ/v2

**Expected behaviour**
4. Currency spec succeeds.

**Actual behaviour**
4. Currency spec fails consistently.

**Screenshots:** 
![Screen Shot 2020-06-02 at 9 11 44 AM](https://user-images.githubusercontent.com/46171897/83524107-1ebb9d00-a4b1-11ea-9f9e-3ae7247e227d.png)

Desktop :
OS: mac OS. Catalina. 10.15

Further investigation by dev is required.

**Comment by giancorderoortiz** [comment]
[currency_e2e_test_fail_2005.zip](https://github.com/SAP/spartacus/files/4717328/currency_e2e_test_fail_2005.zip)

**Comment by KateChuen** [comment]
I think this is because it adds the currency twice in the url.

- When pointing to 1905, this is the url when we change the currency.
https://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/JPY/

- And when pointing to 2005, this is the url (but the site still functions)
https://dev-com-8.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/JPY/JPY/

**Comment by Xymmer** [comment]
flaky in #8216
