### ISSUE TITLE
Anonymous consents disappear after page refresh

### ISSUE THREAD

**Issue by kinga-k** [SAP/spartacus#7915]
Sometimes when page is refreshed anonymous given consents are removed.
Situation visible in video : https://video.sap.com/media/t/1_rit3fydc

**To Reproduce**
Steps to reproduce the behaviour:
1. Environment available on SAP corporate network - requires connecting with VPN
2. Go to https://jsapps.cltq4tr3nt-contextdr1-p3-public.model-t.cc.commerce.ondemand.com/en/USD/?profiletagdebug=true
2. Do the scenario visible on video : https://video.sap.com/media/t/1_rit3fydc

**Expected behaviour**
Consent should not disappear.

**Desktop (please complete the following information):**
 - OS:  mac OS Catalina
 - Browser Chrome Incognito Window

**Additional context**
This is model-T environment (Build 20200501.520200504.1 2005.0.200427005)
Spartacus version : 1.5.3
Related ticket : https://cxjira.sap.com/browse/CDSX-470

**Comment by mirkosoft** [comment]
might be related to https://github.com/SAP/spartacus/issues/6269

**Comment by kinga-k** [comment]
Issue related to 6269 was fixed in  2005 (backed in this case is 2005) and in this scenario there is no logged in user.
Checked also header for consenttemplates request - there is no caching : Cache-Control: no-cache, no-store, max-age=0, must-revalidate
<img width="1535" alt="Screenshot 2020-06-15 at 15 57 29" src="https://user-images.githubusercontent.com/62377026/84668601-2143db00-af24-11ea-92c0-f8b026023d1c.png">

**Comment by Xymmer** [comment]
ok looks like not related to 6269

**Comment by znikola** [comment]
I tried to reproduce this on your server in both Chrome and Firefox, and after maybe 10 tries  I wasn't able to do it.
Is there anything else that I can try?

One note - I see you're using 1.5.3. Does this happen on the latest 1.5.x? (1.5.6 I think).

**Comment by znikola** [comment]
The issue is related to caching. This is the flow that's causing the issue:

- on the initial page load, Spartacus issues request to fetch the CMS data/components, consent templates, language, currency, products, etc.
  - the browser will likely cache some of the requests - usually that would be the currency, language, products, etc.
  - it will cache them with their HTTP response that contains the default consent state of _null_.
- the user accepts all consents from the banner
- in under two minutes that user spend on the site (caching expiration timeout), the user refreshes the page. 
- the browser will load some requests from the cache (currency, language, products...).
  - the loaded requests contain the default consent state (of _null_)
  - these cached requests override the current consent state in Spartacus (where the user accepted them), effectively making it to "disappear"

**Comment by znikola** [comment]
PRs:
- v2.1 PR - https://github.com/SAP/spartacus/pull/8042
- v2.0.x PR - TODO
- v1.5.x PR - TODO

To QA:

- open the devtools, and make sure that the caching is _not_ disabled when the devtools are open
- open Spartacus
- accept the consents from the banner
- refresh in under two minutes spent on the site
- check the consents - the state should be the same as before the refresh

Acceptance criteria - in the opened devtools, verify that some requests are indeed coming from the disk cache - if this is the case, _and_ the state is the same as before the refresh, the bug is considered as squashed :)

**Comment by Xymmer** [comment]
Let's make sure to backport to 2.0.x also
ah wait that's what nik already wrote :)
