### ISSUE TITLE
Wrong occ prefix generated on windows

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#7951]
When running installation script on windows app config's occ prefix taken from script's config `OCC_PREFIX` variable is being generated wrong:
![image](https://user-images.githubusercontent.com/788092/84393071-6b168380-abfb-11ea-91d7-bf5927f82791.png)
To reproduce it try running the script on windows machine with `OCC_PREFIX` set to absolute path. @marlass correct me if I'm wrong.

**Comment by marlass** [comment]
I had in config `/rest/v2/`. I am guessing that if a string starts with `/` some special bash utility is run to provide full path. Need to confirm by running with prefix without `/` at the beggining.

**Comment by giancorderoortiz** [comment]
Which Windows version ?

**Comment by marlass** [comment]
Any Windows 10. Maybe even older versions

**Comment by Xymmer** [comment]
tested on 3.0 and windows, can it be closed?

**Comment by Xymmer** [comment]
related to install script

**Comment by marlass** [comment]
Still happening

**Comment by psmul** [comment]
After investigating the topic, it turns out that the problem lies in low-level windows path conversion, which is not easy to work around with. At some point of running commands, windows envs are using MSYS mechanisms to detect whether passed argument is a path. For some reason pattern `/test/123` cannot be escaped.
Because this case is particular only to Windows machines we will only adjust our method of using config for release process. 
Another part of the solution will be applied within `OccEndpointsService` refactor.
