### ISSUE TITLE
Breadcrumbs i18n namespace shouldn't be bounded to the organization i18n chunk

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#8305]

**Comment by Platonn** [comment]
Renamed the ticket.

We can't figure out the organization CMS page name for the child pages, becuase there is no notion about the parent page of any child page in the CMS page data. That's why we need to hardcode it in the PageMetaResolver (while keeping it extendable).

Let's just don't bound namespace `breadcrumbs.XXX` to the `organization.json` chunk.
