### ISSUE TITLE
feat: Create new "Blue" theme

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#8511]
↓↓ **For updates/status: Scroll down to read comments at the bottom.** ↓↓

Create a separate theme updating colors and styling without introducing new elements.

Link to visuals
https://app.zeplin.io/project/5f062d700cf6485b7607df80/dashboard?sid=5f1e47e65a39ed3775c3c3d7

**Comment by developpeurweb** [comment]
The approach validated by the architect for this issue is the one reflected on PR #9571 most of the styles for the blue-theme are in place, we are only missing the following parts:

- Strategy for fixing Bootstrap's overriding variables on buttons (hex colors and radius)
- Backend switch (for adding theme class to `<cx-storefront>` tag )

**Comment by developpeurweb** [comment]
A switchless **hardcoded** version of the blue-theme was created and referenced in this PR #9539 which is **NOT to be merged**, it's only for demonstration purposes.

**Comment by developpeurweb** [comment]
cc @tobi-or-not-tobi to stay in the loop of this ticket's history, as we need his input/strategy on both missing parts referred to in previous comments.
