### ISSUE TITLE
Group Status is not set when navigating to group with slow network speed and then setting attribute in old group.

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#8594]
- Set network to slow
- Navigate to next group
- Set an attribute before the navigation takes place
--> The user navigates to the next group then after the update is done, the old group is loaded, group status is not set for next group. (Clarify if this is a bug or a wanted "feature")

**Comment by ChristophHi** [comment]
From my point of view this is fine 
(1) because the user in this case is kind of cancelling the navigation to the next group, no real visit happens
(2) because building this for this exceptional case seems to be over-engineered. The normal process is that if user clicks 'next', they wait for the next group to appear

**Comment by ChristophHi** [comment]
Jutta agrees, so I am going to close this issue
