### ISSUE TITLE
[Crit] Remove configurator specific logic from Add-to-cart component

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9179]
The TS logic of `add-to-cart.component` is now depending on the existence of the property `product.configurable`. See the actual diff:
   ![obraz](https://user-images.githubusercontent.com/4001059/95074497-f5d14000-070e-11eb-8ca5-cb29d23a9e79.png)
   - Idea how to move it out: to be investigated

**Comment by ChristophHi** [comment]
The standard SPA way of figuring out whether to append entry or to increase qty is wrong, so is our extension. Because the commerce backend decides whether a new item is merged to existing ones, this is hook based and not specifically bound to the product configuration process. Therefore SPA should just check if the backend created a new entry or not

**Comment by ChristophHi** [comment]
We will track this through https://github.com/SAP/spartacus/issues/9247 and perform this change independently of configurators. Other business processes face the same issue
