### ISSUE TITLE
UX for B2B Multi-Dimensional throughout (no order grid) (XS)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9265]
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Multi-Dimensional+Products
This is for integraton throughout Spartacus, but not order grid, which is phase 2

**Comment by vekterdude** [comment]
Catalog:
When displaying search or category results, only one product representing the variant family should appear.

In the accelerator catalog there are ways to select variants from a quick view feature. Is including this (restyling, mostly) this part of the story. If not, does add to cart button in the catalog need to be turned off when variants are turned on?

![quick_view_menu](https://user-images.githubusercontent.com/44620139/96772039-861ab080-13b0-11eb-91c0-b994259905a3.png)

![quickview_flyout](https://user-images.githubusercontent.com/44620139/96772093-9fbbf800-13b0-11eb-99a7-2e1e38ee606f.png)

**Comment by vekterdude** [comment]
Shopping Cart:
Behavior should be similar to variants.

At present, there does not appear to be even a way back to the pdp to edit the variants from the shopping cart.

![location_of_edit_delete](https://user-images.githubusercontent.com/44620139/96772703-8798a880-13b1-11eb-9df3-5f0332ca7d51.png)

We can add an edit action to the menu pictured above, or we can open the quick view window as a modal (probably too much work)
The accelerator handled this via returning the user to the pdp since the customer may add more variants than the 3 out of the box.
Many tools like quick order in the near future may benefit from a variant editing component and SPA is single page, so location should not matter, no? But there is effort to think about.

**Comment by vekterdude** [comment]
Checkout:
Phase 1 would mean we display multi-dimensional products as individual products (like variants).

Again like the shopping cart, users can usually edit their selections until the final review of the shopping cart. Are we proposing that:
1. There is no editing - user must delete the product and start again with the correct variant restarting their journey in the pdp including manually finding the product again and adding the edited one?
2. The user edits the variant by being 'automagically' returned to the pdp (as per accelerator) and clicking an 'update' button rather than an 'add to cart' button and is then automagically returned to the checkout?
3. A modal is opened (similar to quickview) and the user is able to change the variant or quantity without leaving the checkout?

**Comment by Xymmer** [comment]
@vekterdude :wave: 
 phase 1 is basic multi-d support so it's almost exactly like variants, which work as described:
- only one product will appear representing multi-d (that's a backend search results thing)
- no preview in search/categories (that would be a new feature)
- a multi-d product added to cart is an individual sku 
- no editing (we actually display order grid in cart in accelerator but this could be seen from another pov too)

Given this info, can we assume that re-using the variant ui for multi-d is viable and we can close this issue?

**Comment by jeannewalters** [comment]
@vekterdude Anthony will provide feedback to Bill on phase 1 by 11/6.

**Comment by vekterdude** [comment]
After an extensive review and meeting with Bill Marcotte it was decided that the difference between (architectural) variants and multi-dimensional products are backend only. They are exactly the same thing from the user perspective. They are selected the same and the resulting selection is displayed the same, so the existing UI for variants will perfectly handle multi-dimensional products as far as we can tell at this time.

**Comment by Xymmer** [comment]
Source of truth updated: https://cxwiki.sap.com/display/spar/B2B+Multi-D+Products+SoT+Phase1++Nov+2020
