### ISSUE TITLE
No suggestion on what is a valid password 

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9357]
**Is your feature request related to a problem? Please describe.**
When changing a user's password, there is no suggestion of an acceptable password format and The user had to guess the requirements. 

**Describe the solution you'd like**
Indicate in some inline help text what a valid password format is. By trial and error, the requirements were discovered to be the following - 

- minimum of 6 characters
- at least 1 number (0-10
- at least 1 capital letter (A-Z)
- at least 1 special character (!@#$%^&*)

**Steps to Reproduce**
1. Go to users 
2. Click on an existing User to reveal the Details panel
3. Click on "Change Password" 
4. In the Change Password panel, enter a new password
5. Observe that the requirement for a valid password format is not indicated

**Additional context**
<img width="562" alt="Screen Shot 2020-10-12 at 3 14 29 PM" src="https://user-images.githubusercontent.com/15215400/96158934-ae4e6f00-0ed9-11eb-8a24-b21ad75f923c.png">

**Comment by giancorderoortiz** [comment]
This is actually a very good observation. Conversations I've heard in the past have centered about not providing much information for security purposes and to force user to deal with administrator directly on this issue. 
Perhaps things have changed. 
Input from @tobi-or-not-tobi  or @meeque would be nice.

**Comment by meeque** [comment]
First off, I wonder if this problem also affects other places where a user sets a password? E.g. on account registration? If so, it would be great to have a consistent solution for all of these situations.

From a security perspective, there is no requirement to hide passphrase policies from the user. If such policies are being enforced, they should be communicated to the user clearly. Either upfront (i.e. before the user attempts to enter a password) or ondemand (i.e. when password validation fails).

But how to achieve that? 

In the end, password policy must be enforced by the server-side. Luckily, this seems to be the case here. Spartacus merely calls certain SAP Commerce OCC APIs, which either process the password successfully or respond with an error. These same server-side APIs should also be responsible for communicating specific validation errors.

I had a quick glance at the server-side source code (OCC API). It seems that it uses a generic validation framework that also emits localized error messages for specific password validation errors. E.g.:
```
field.password.notallowed.chars=Password contains not allowed characters
field.password.min.one.number=Password should contain at least one number
field.password.min.one.uppercase=Password should contain at least one uppercase character
field.password.min.one.special.char=Password should contain at least one special character
field.password.min.six.characters=Password should be at least six characters long
```
It also seems that such error messages are exposed in the error response of the OCC API. So Spartacus should be in a good position to relay them to the user.

**Comment by meeque** [comment]
On a side note: 

There is also the possibility that Spartacus could reimplement the same validation logic as is used on the server-side. That would allow Spartacus to emit its own error messages, if necessary. However, I would recommend against this, because server-side enforcement of password policies could be subject to change, and it would be hard to keep Spartacus in sync with that.

In fact, I thought that SAP Commerce provides [customizable password policies](https://help.sap.com/viewer/d0224eca81e249cb821f2cdf45a82ace/2005/en-US/dfeec89a46c64774892b46936d65d530.html). However, the OCC API implementation also seems to contain its own, hard-coded password validation logic. It seems to implement the same rules that @saad-mo reported above. Not sure how those two mechanisms interact?

**Comment by tobi-or-not-tobi** [comment]
To answer a few questions that came up in this ticket:
1. There's only one password validator in Spartacus, which is used during user registration and also the creation of users in the organization admin
2. Spartacus already implemented client side validation, which is aligned with the default validation from the backend
3. The standard password validation is not extensible, which means that customers who require an alternative password policy (either by changing backend, or by using an external IdP), can not reflect this in Spartacus. 
4. There's simple a lack of good experience as Spartacus doesn't provide validation on the password.

This issue is about the last point, which is already logged at #1590. I think that's a good ticket, and i'm closing this to keep the conversation at that ticket.
