### ISSUE TITLE
Unable to Sort MyCompany Users by Name or Unit

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9557]
**Steps to Reproduce:** 
1. Navigate to SPA B2B powertools storefront. 
2. Login as admin (i.e. linda wolf)
3. From My Account menu, select My Company
4. Select Users. 
5. In the Users page, attempt to change sort order to either byname or by unit. 

**Expected Results:** 
5. Order changes according to sort. 

**Actual Results:** 
5. Ordering of users doesn't change. There is no call made to backend.

**Comment by giancorderoortiz** [comment]
![sortByName](https://user-images.githubusercontent.com/46171897/97442855-b0182980-1900-11eb-86d1-e36ab76e930e.png)
![sortByUnit](https://user-images.githubusercontent.com/46171897/97442857-b0b0c000-1900-11eb-9d90-e01a10ecb902.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-28 at 9 46 10 AM](https://user-images.githubusercontent.com/46171897/97444357-72b49b80-1902-11eb-9cbf-adb9ba45543f.png)

**Comment by Pucek9** [comment]
I think you were jumping between sorting options and didn't observe request, because they were cached already. If you refresh the page and change sorting code, you will see new request with different query params 

Initial:
Request URL: https://spartacus-dev3.eastus.cloudapp.azure.com:9002/occ/v2/powertools-spa/users/current/orgCustomers?pageSize=10&sort=byName&lang=en&curr=USD

After change code to sort by unit:
Request URL: https://spartacus-dev3.eastus.cloudapp.azure.com:9002/occ/v2/powertools-spa/users/current/orgCustomers?currentPage=0&pageSize=10&sort=byName&totalPages=24&totalResults=234&lang=en&curr=USD

Requests above are different, but second one seems wrong, it should be:
Request URL: https://spartacus-dev3.eastus.cloudapp.azure.com:9002/occ/v2/powertools-spa/users/current/orgCustomers?pageSize=10&sort=byUnit&lang=en&curr=USD

**Comment by Pucek9** [comment]
Additionally, query params like `totalPages` and `totalResults` are added to all requests while change sorting/pagination (eg. cost centers, unit/approvers/assign). That's unexpected. Created new issue for that: #9709

**Comment by Pucek9** [comment]
To fix an issue it's enough remove that part:
![image](https://user-images.githubusercontent.com/8040837/98565422-e44efb00-22ad-11eb-8955-304a7ecda561.png)
