### ISSUE TITLE
Text is too close button in units/users

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9561]
On mobile view in http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Services/users it seems like this:
![image](https://user-images.githubusercontent.com/8040837/97447920-5cbdcf80-1930-11eb-8667-a7f1d201d560.png)

**Comment by wangzixi-diablo** [comment]
Hello @Pucek9,

Just to be sure, I assume the expected behavior in Mobile view: there SHOULD also be some space between column "name" and "roles", to be consistent with the appearance opened in PC browser? Is my understanding correct? Thanks a lot!

![image](https://user-images.githubusercontent.com/58975336/100696045-8fdefd00-33cd-11eb-9b3a-7f8684610a0e.png)

Best Regards,
Jerry

**Comment by wangzixi-diablo** [comment]
![image](https://user-images.githubusercontent.com/58975336/100852013-e11be900-34c0-11eb-8b99-8c6435b48884.png)
![image](https://user-images.githubusercontent.com/58975336/100852139-0577c580-34c1-11eb-83df-fbda1ed5c2d2.png)

**Comment by Pucek9** [comment]
I think, your changes are affecting desktop view too:
![image](https://user-images.githubusercontent.com/8040837/101217211-44547980-3681-11eb-9f30-b128a72177c9.png)
compared your screenshot with my develop

**Comment by wangzixi-diablo** [comment]
this issue is already fixed by PR: https://github.com/SAP/spartacus/pull/10177
