### ISSUE TITLE
Unify user roles checkboxes

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9671]
User form (user -> create/edit & unit -> users -> create) uses different styles for checkboxes, than change roles form (unit -> users -> roles). 
![image](https://user-images.githubusercontent.com/8040837/98262746-41813e80-1f86-11eb-81ed-363aea353dc5.png)
IMO the left side seems better, let's fix UnitUserRolesFormComponent.

**Comment by wangzixi-diablo** [comment]
|  file name   | checkbox control class  
|  ----  | ----  
| unit-user-roles.component.html  | form-check(its parent's class)
| user-form.component.html  | form-check-input (its own class)

* screenshot of checkbox class in user-form.component.html: 
![image](https://user-images.githubusercontent.com/58975336/103085739-8e47d400-461d-11eb-965b-f31bbb3a6849.png)

I guess this class is not valid, since there's no corresponding settings for it in any .scss file.
====

* screenshot for checkbox in unit-user-role.component.html:
 
![image](https://user-images.githubusercontent.com/58975336/103085871-eda5e400-461d-11eb-9375-e13dba1e44f2.png)
====

* html source code and css style for checkbox in user form:

![image](https://user-images.githubusercontent.com/58975336/103086011-53926b80-461e-11eb-8fa3-9653f8d59e69.png)
====

* html source code and css style for checkbox in unit-user-role html:

![image](https://user-images.githubusercontent.com/58975336/103086288-34480e00-461f-11eb-84fa-919b65c36b74.png)

I have compared both, and no difference found between the two.

### My question

Via my research, I found the two checkboxes as you mentioned do have the same styles already, so no need to unify them.
